#pragma once

#include "NamedTag.hpp"

struct Block;
using BlockTag = NamedTag<const Block*>;

struct BlockTags {
    static BlockTag WOOL;
    static BlockTag PLANKS;
    static BlockTag STONE_BRICKS;
    static BlockTag WOODEN_BUTTONS;
    static BlockTag BUTTONS;
    static BlockTag CARPETS;
    static BlockTag WOODEN_DOORS;
    static BlockTag WOODEN_STAIRS;
    static BlockTag WOODEN_SLABS;
    static BlockTag WOODEN_FENCES;
    static BlockTag PRESSURE_PLATES;
    static BlockTag WOODEN_PRESSURE_PLATES;
    static BlockTag STONE_PRESSURE_PLATES;
    static BlockTag WOODEN_TRAPDOORS;
    static BlockTag DOORS;
    static BlockTag SAPLINGS;
    static BlockTag LOGS_THAT_BURN;
    static BlockTag LOGS;
    static BlockTag DARK_OAK_LOGS;
    static BlockTag OAK_LOGS;
    static BlockTag BIRCH_LOGS;
    static BlockTag ACACIA_LOGS;
    static BlockTag JUNGLE_LOGS;
    static BlockTag SPRUCE_LOGS;
    static BlockTag CRIMSON_STEMS;
    static BlockTag WARPED_STEMS;
    static BlockTag BANNERS;
    static BlockTag SAND;
    static BlockTag STAIRS;
    static BlockTag SLABS;
    static BlockTag WALLS;
    static BlockTag ANVIL;
    static BlockTag RAILS;
    static BlockTag LEAVES;
    static BlockTag TRAPDOORS;
    static BlockTag SMALL_FLOWERS;
    static BlockTag BEDS;
    static BlockTag FENCES;
    static BlockTag TALL_FLOWERS;
    static BlockTag FLOWERS;
    static BlockTag PIGLIN_REPELLENTS;
    static BlockTag GOLD_ORES;
    static BlockTag NON_FLAMMABLE_WOOD;
    static BlockTag FLOWER_POTS;
    static BlockTag ENDERMAN_HOLDABLE;
    static BlockTag ICE;
    static BlockTag VALID_SPAWN;
    static BlockTag IMPERMEABLE;
    static BlockTag UNDERWATER_BONEMEALS;
    static BlockTag CORAL_BLOCKS;
    static BlockTag WALL_CORALS;
    static BlockTag CORAL_PLANTS;
    static BlockTag CORALS;
    static BlockTag BAMBOO_PLANTABLE_ON;
    static BlockTag STANDING_SIGNS;
    static BlockTag WALL_SIGNS;
    static BlockTag SIGNS;
    static BlockTag DRAGON_IMMUNE;
    static BlockTag WITHER_IMMUNE;
    static BlockTag WITHER_SUMMON_BASE_BLOCKS;
    static BlockTag BEEHIVES;
    static BlockTag CROPS;
    static BlockTag BEE_GROWABLES;
    static BlockTag PORTALS;
    static BlockTag FIRE;
    static BlockTag NYLIUM;
    static BlockTag WART_BLOCKS;
    static BlockTag BEACON_BASE_BLOCKS;
    static BlockTag SOUL_SPEED_BLOCKS;
    static BlockTag WALL_POST_OVERRIDE;
    static BlockTag CLIMBABLE;
    static BlockTag SHULKER_BOXES;
    static BlockTag HOGLIN_REPELLENTS;
    static BlockTag SOUL_FIRE_BASE_BLOCKS;
    static BlockTag STRIDER_WARM_BLOCKS;
    static BlockTag CAMPFIRES;
    static BlockTag GUARDED_BY_PIGLINS;
    static BlockTag PREVENT_MOB_SPAWNING_INSIDE;
    static BlockTag FENCE_GATES;
    static BlockTag UNSTABLE_BOTTOM_CENTER;
    static BlockTag MUSHROOM_GROW_BLOCK;
    static BlockTag INFINIBURN_OVERWORLD;
    static BlockTag INFINIBURN_NETHER;
    static BlockTag INFINIBURN_END;
    static BlockTag BASE_STONE_OVERWORLD;
    static BlockTag BASE_STONE_NETHER;

    static void registerTags();
};