#include "Materials.hpp"

Material* Materials::AIR;
Material* Materials::STRUCTURE_VOID;
Material* Materials::PORTAL;
Material* Materials::CARPET;
Material* Materials::PLANTS;
Material* Materials::OCEAN_PLANT;
Material* Materials::TALL_PLANTS;
Material* Materials::NETHER_PLANTS;
Material* Materials::SEA_GRASS;
Material* Materials::WATER;
Material* Materials::BUBBLE_COLUMN;
Material* Materials::LAVA;
Material* Materials::SNOW;
Material* Materials::FIRE;
Material* Materials::MISCELLANEOUS;
Material* Materials::WEB;
Material* Materials::REDSTONE_LIGHT;
Material* Materials::CLAY;
Material* Materials::EARTH;
Material* Materials::ORGANIC;
Material* Materials::PACKED_ICE;
Material* Materials::SAND;
Material* Materials::SPONGE;
Material* Materials::SHULKER;
Material* Materials::WOOD;
Material* Materials::NETHER_WOOD;
Material* Materials::BAMBOO_SAPLING;
Material* Materials::BAMBOO;
Material* Materials::WOOL;
Material* Materials::TNT;
Material* Materials::LEAVES;
Material* Materials::GLASS;
Material* Materials::ICE;
Material* Materials::CACTUS;
Material* Materials::ROCK;
Material* Materials::IRON;
Material* Materials::SNOW_BLOCK;
Material* Materials::ANVIL;
Material* Materials::BARRIER;
Material* Materials::PISTON;
Material* Materials::CORAL;
Material* Materials::GOURD;
Material* Materials::DRAGON_EGG;
Material* Materials::CAKE;

void Materials::registerMaterials() {
    AIR = Material::Builder(MaterialColors::AIR).doesNotBlockMovement().notOpaque().notSolid().replaceable().build();
    STRUCTURE_VOID = Material::Builder(MaterialColors::AIR).doesNotBlockMovement().notOpaque().notSolid().replaceable().build();
    PORTAL = Material::Builder(MaterialColors::AIR).doesNotBlockMovement().notOpaque().notSolid().pushBlocks().build();
    CARPET = Material::Builder(MaterialColors::WOOL).doesNotBlockMovement().notOpaque().notSolid().flammable().build();
    PLANTS = Material::Builder(MaterialColors::FOLIAGE).doesNotBlockMovement().notOpaque().notSolid().pushDestroys().build();
    OCEAN_PLANT = Material::Builder(MaterialColors::WATER).doesNotBlockMovement().notOpaque().notSolid().pushDestroys().build();
    TALL_PLANTS = Material::Builder(MaterialColors::FOLIAGE).doesNotBlockMovement().notOpaque().notSolid().pushDestroys().replaceable().flammable().build();
    NETHER_PLANTS = Material::Builder(MaterialColors::FOLIAGE).doesNotBlockMovement().notOpaque().notSolid().pushDestroys().replaceable().build();
    SEA_GRASS = Material::Builder(MaterialColors::WATER).doesNotBlockMovement().notOpaque().notSolid().pushDestroys().replaceable().build();
    WATER = Material::Builder(MaterialColors::WATER).doesNotBlockMovement().notOpaque().notSolid().pushDestroys().replaceable().liquid().build();
    BUBBLE_COLUMN = Material::Builder(MaterialColors::WATER).doesNotBlockMovement().notOpaque().notSolid().pushDestroys().replaceable().liquid().build();
    LAVA = Material::Builder(MaterialColors::TNT).doesNotBlockMovement().notOpaque().notSolid().pushDestroys().replaceable().liquid().build();
    SNOW = Material::Builder(MaterialColors::SNOW).doesNotBlockMovement().notOpaque().notSolid().pushDestroys().replaceable().build();
    FIRE = Material::Builder(MaterialColors::AIR).doesNotBlockMovement().notOpaque().notSolid().pushDestroys().replaceable().build();
    MISCELLANEOUS = Material::Builder(MaterialColors::AIR).doesNotBlockMovement().notOpaque().notSolid().pushDestroys().build();
    WEB = Material::Builder(MaterialColors::WOOL).doesNotBlockMovement().notOpaque().pushDestroys().build();
    REDSTONE_LIGHT = Material::Builder(MaterialColors::AIR).build();
    CLAY = Material::Builder(MaterialColors::CLAY).build();
    EARTH = Material::Builder(MaterialColors::DIRT).build();
    ORGANIC = Material::Builder(MaterialColors::GRASS).build();
    PACKED_ICE = Material::Builder(MaterialColors::ICE).build();
    SAND = Material::Builder(MaterialColors::SAND).build();
    SPONGE = Material::Builder(MaterialColors::YELLOW).build();
    SHULKER = Material::Builder(MaterialColors::PURPLE).build();
    WOOD = Material::Builder(MaterialColors::WOOD).flammable().build();
    NETHER_WOOD = Material::Builder(MaterialColors::WOOD).build();
    BAMBOO_SAPLING = Material::Builder(MaterialColors::WOOD).flammable().pushDestroys().doesNotBlockMovement().build();
    BAMBOO = Material::Builder(MaterialColors::WOOD).flammable().pushDestroys().build();
    WOOL = Material::Builder(MaterialColors::WOOL).flammable().build();
    TNT = Material::Builder(MaterialColors::TNT).flammable().notOpaque().build();
    LEAVES = Material::Builder(MaterialColors::FOLIAGE).flammable().notOpaque().pushDestroys().build();
    GLASS = Material::Builder(MaterialColors::AIR).notOpaque().build();
    ICE = Material::Builder(MaterialColors::ICE).notOpaque().build();
    CACTUS = Material::Builder(MaterialColors::FOLIAGE).notOpaque().pushDestroys().build();
    ROCK = Material::Builder(MaterialColors::STONE).build();
    IRON = Material::Builder(MaterialColors::IRON).build();
    SNOW_BLOCK = Material::Builder(MaterialColors::SNOW).build();
    ANVIL = Material::Builder(MaterialColors::IRON).pushBlocks().build();
    BARRIER = Material::Builder(MaterialColors::AIR).pushBlocks().build();
    PISTON = Material::Builder(MaterialColors::STONE).pushBlocks().build();
    CORAL = Material::Builder(MaterialColors::FOLIAGE).pushDestroys().build();
    GOURD = Material::Builder(MaterialColors::FOLIAGE).pushDestroys().build();
    DRAGON_EGG = Material::Builder(MaterialColors::FOLIAGE).pushDestroys().build();
    CAKE = Material::Builder(MaterialColors::AIR).pushDestroys().build();
}
