#include "Biomes.hpp"
#include "Biome.hpp"

#include "BiomeMaker.hpp"

std::map<int, std::unique_ptr<Biome>> Biomes::biomes;
std::map<std::string_view, Biome*> Biomes::table;

Biome* Biomes::OCEAN;
Biome* Biomes::PLAINS;
Biome* Biomes::DESERT;
Biome* Biomes::MOUNTAINS;
Biome* Biomes::FOREST;
Biome* Biomes::TAIGA;
Biome* Biomes::SWAMP;
Biome* Biomes::RIVER;
Biome* Biomes::NETHER_WASTES;
Biome* Biomes::THE_END;
Biome* Biomes::FROZEN_OCEAN;
Biome* Biomes::FROZEN_RIVER;
Biome* Biomes::SNOWY_TUNDRA;
Biome* Biomes::SNOWY_MOUNTAINS;
Biome* Biomes::MUSHROOM_FIELDS;
Biome* Biomes::MUSHROOM_FIELD_SHORE;
Biome* Biomes::BEACH;
Biome* Biomes::DESERT_HILLS;
Biome* Biomes::WOODED_HILLS;
Biome* Biomes::TAIGA_HILLS;
Biome* Biomes::MOUNTAIN_EDGE;
Biome* Biomes::JUNGLE;
Biome* Biomes::JUNGLE_HILLS;
Biome* Biomes::JUNGLE_EDGE;
Biome* Biomes::DEEP_OCEAN;
Biome* Biomes::STONE_SHORE;
Biome* Biomes::SNOWY_BEACH;
Biome* Biomes::BIRCH_FOREST;
Biome* Biomes::BIRCH_FOREST_HILLS;
Biome* Biomes::DARK_FOREST;
Biome* Biomes::SNOWY_TAIGA;
Biome* Biomes::SNOWY_TAIGA_HILLS;
Biome* Biomes::GIANT_TREE_TAIGA;
Biome* Biomes::GIANT_TREE_TAIGA_HILLS;
Biome* Biomes::WOODED_MOUNTAINS;
Biome* Biomes::SAVANNA;
Biome* Biomes::SAVANNA_PLATEAU;
Biome* Biomes::BADLANDS;
Biome* Biomes::WOODED_BADLANDS_PLATEAU;
Biome* Biomes::BADLANDS_PLATEAU;
Biome* Biomes::SMALL_END_ISLANDS;
Biome* Biomes::END_MIDLANDS;
Biome* Biomes::END_HIGHLANDS;
Biome* Biomes::END_BARRENS;
Biome* Biomes::WARM_OCEAN;
Biome* Biomes::LUKEWARM_OCEAN;
Biome* Biomes::COLD_OCEAN;
Biome* Biomes::DEEP_WARM_OCEAN;
Biome* Biomes::DEEP_LUKEWARM_OCEAN;
Biome* Biomes::DEEP_COLD_OCEAN;
Biome* Biomes::DEEP_FROZEN_OCEAN;
Biome* Biomes::THE_VOID;
Biome* Biomes::SUNFLOWER_PLAINS;
Biome* Biomes::DESERT_LAKES;
Biome* Biomes::GRAVELLY_MOUNTAINS;
Biome* Biomes::FLOWER_FOREST;
Biome* Biomes::TAIGA_MOUNTAINS;
Biome* Biomes::SWAMP_HILLS;
Biome* Biomes::ICE_SPIKES;
Biome* Biomes::MODIFIED_JUNGLE;
Biome* Biomes::MODIFIED_JUNGLE_EDGE;
Biome* Biomes::TALL_BIRCH_FOREST;
Biome* Biomes::TALL_BIRCH_HILLS;
Biome* Biomes::DARK_FOREST_HILLS;
Biome* Biomes::SNOWY_TAIGA_MOUNTAINS;
Biome* Biomes::GIANT_SPRUCE_TAIGA;
Biome* Biomes::GIANT_SPRUCE_TAIGA_HILLS;
Biome* Biomes::MODIFIED_GRAVELLY_MOUNTAINS;
Biome* Biomes::SHATTERED_SAVANNA;
Biome* Biomes::SHATTERED_SAVANNA_PLATEAU;
Biome* Biomes::ERODED_BADLANDS;
Biome* Biomes::MODIFIED_WOODED_BADLANDS_PLATEAU;
Biome* Biomes::MODIFIED_BADLANDS_PLATEAU;
Biome* Biomes::BAMBOO_JUNGLE;
Biome* Biomes::BAMBOO_JUNGLE_HILLS;
Biome* Biomes::SOUL_SAND_VALLEY;
Biome* Biomes::CRIMSON_FOREST;
Biome* Biomes::WARPED_FOREST;
Biome* Biomes::BASALT_DELTAS;

Biome* Biomes::registerBiome(int id, std::string_view name, Biome* biome) {
    biomes[id] = std::unique_ptr<Biome>(biome);
    table[name] = biome;
    return biome;
}

void Biomes::registerBiomes() {
    using namespace std::string_view_literals;

    OCEAN = registerBiome(0, "ocean"sv, BiomeMaker::makeOceanBiome(false));
    PLAINS = registerBiome(1, "plains"sv, BiomeMaker::makePlainsBiome(false));
    DESERT = registerBiome(2, "desert"sv, BiomeMaker::makeDesertBiome(0.125F, 0.05F, true, true, true));
    MOUNTAINS = registerBiome(3, "mountains"sv, BiomeMaker::makeMountainBiome(1.0F, 0.5F, ConfiguredSurfaceBuilders::MOUNTAIN, false));
    FOREST = registerBiome(4, "forest"sv, BiomeMaker::makeForestBiome(0.1F, 0.2F));
    TAIGA = registerBiome(5, "taiga"sv, BiomeMaker::makeTaigaBiome(0.2F, 0.2F, false, false, true, false));
    SWAMP = registerBiome(6, "swamp"sv,BiomeMaker::makeGenericSwampBiome(-0.2F, 0.1F, false));
    RIVER = registerBiome(7, "river"sv, BiomeMaker::makeRiverBiome(-0.5F, 0.0F, 0.5F, 4159204, false));
    NETHER_WASTES = registerBiome(8, "nether_wastes"sv, BiomeMaker::makeNetherWastesBiome());
    THE_END = registerBiome(9, "the_end"sv, BiomeMaker::makeTheEndBiome());
    FROZEN_OCEAN = registerBiome(10, "frozen_ocean"sv, BiomeMaker::makeFrozenOceanBiome(false));
    FROZEN_RIVER = registerBiome(11, "frozen_river"sv, BiomeMaker::makeRiverBiome(-0.5F, 0.0F, 0.0F, 3750089, true));
    SNOWY_TUNDRA = registerBiome(12, "snowy_tundra"sv, BiomeMaker::makeSnowyBiome(0.125F, 0.05F, false, false));
    SNOWY_MOUNTAINS = registerBiome(13, "snowy_mountains"sv, BiomeMaker::makeSnowyBiome(0.45F, 0.3F, false, true));
    MUSHROOM_FIELDS = registerBiome(14, "mushroom_fields"sv, BiomeMaker::makeMushroomBiome(0.2F, 0.3F));
    MUSHROOM_FIELD_SHORE = registerBiome(15, "mushroom_field_shore"sv, BiomeMaker::makeMushroomBiome(0.0F, 0.025F));
    BEACH = registerBiome(16, "beach"sv, BiomeMaker::makeBeachBiome(0.0F, 0.025F, 0.8F, 0.4F, 4159204, false, false));
    DESERT_HILLS = registerBiome(17, "desert_hills"sv, BiomeMaker::makeDesertBiome(0.45F, 0.3F, false, true, false));
    WOODED_HILLS = registerBiome(18, "wooded_hills"sv, BiomeMaker::makeForestBiome(0.45F, 0.3F));
    TAIGA_HILLS = registerBiome(19, "taiga_hills"sv, BiomeMaker::makeTaigaBiome(0.45F, 0.3F, false, false, false, false));
    MOUNTAIN_EDGE = registerBiome(20, "mountain_edge"sv, BiomeMaker::makeMountainBiome(0.8F, 0.3F, ConfiguredSurfaceBuilders::GRASS, true));
    JUNGLE = registerBiome(21, "jungle"sv, BiomeMaker::makeJungleBiome());
    JUNGLE_HILLS = registerBiome(22, "jungle_hills"sv, BiomeMaker::makeJungleHillsBiome());
    JUNGLE_EDGE = registerBiome(23, "jungle_edge"sv, BiomeMaker::makeJungleEdgeBiome());
    DEEP_OCEAN = registerBiome(24, "deep_ocean"sv, BiomeMaker::makeOceanBiome(true));
    STONE_SHORE = registerBiome(25, "stone_shore"sv, BiomeMaker::makeBeachBiome(0.1F, 0.8F, 0.2F, 0.3F, 4159204, false, true));
    SNOWY_BEACH = registerBiome(26, "snowy_beach"sv, BiomeMaker::makeBeachBiome(0.0F, 0.025F, 0.05F, 0.3F, 4020182, true, false));
    BIRCH_FOREST = registerBiome(27, "birch_forest"sv, BiomeMaker::makeBirchForestBiome(0.1F, 0.2F, false));
    BIRCH_FOREST_HILLS = registerBiome(28, "birch_forest_hills"sv, BiomeMaker::makeBirchForestBiome(0.45F, 0.3F, false));
    DARK_FOREST = registerBiome(29, "dark_forest"sv, BiomeMaker::makeDarkForestBiome(0.1F, 0.2F, false));
    SNOWY_TAIGA = registerBiome(30, "snowy_taiga"sv, BiomeMaker::makeTaigaBiome(0.2F, 0.2F, true, false, false, true));
    SNOWY_TAIGA_HILLS = registerBiome(31, "snowy_taiga_hills"sv, BiomeMaker::makeTaigaBiome(0.45F, 0.3F, true, false, false, false));
    GIANT_TREE_TAIGA = registerBiome(32, "giant_tree_taiga"sv, BiomeMaker::makeGiantTaigaBiome(0.2F, 0.2F, 0.3F, false));
    GIANT_TREE_TAIGA_HILLS = registerBiome(33, "giant_tree_taiga_hills"sv, BiomeMaker::makeGiantTaigaBiome(0.45F, 0.3F, 0.3F, false));
    WOODED_MOUNTAINS = registerBiome(34, "wooded_mountains"sv, BiomeMaker::makeMountainBiome(1.0F, 0.5F, ConfiguredSurfaceBuilders::GRASS, true));
    SAVANNA = registerBiome(35, "savanna"sv, BiomeMaker::makeSavannaBiome(0.125F, 0.05F, 1.2F, false, false));
    SAVANNA_PLATEAU = registerBiome(36, "savanna_plateau"sv, BiomeMaker::makeSavannaPlateauBiome());
    BADLANDS = registerBiome(37, "badlands"sv, BiomeMaker::makeBadlandsBiome(0.1F, 0.2F, false));
    WOODED_BADLANDS_PLATEAU = registerBiome(38, "wooded_badlands_plateau"sv, BiomeMaker::makeWoodedBadlandsPlateauBiome(1.5F, 0.025F));
    BADLANDS_PLATEAU = registerBiome(39, "badlands_plateau"sv, BiomeMaker::makeBadlandsBiome(1.5F, 0.025F, true));
    SMALL_END_ISLANDS = registerBiome(40, "small_end_islands"sv, BiomeMaker::makeSmallEndIslandsBiome());
    END_MIDLANDS = registerBiome(41, "end_midlands"sv, BiomeMaker::makeEndMidlandsBiome());
    END_HIGHLANDS = registerBiome(42, "end_highlands"sv, BiomeMaker::makeEndHighlandsBiome());
    END_BARRENS = registerBiome(43, "end_barrens"sv, BiomeMaker::makeEndBarrensBiome());
    WARM_OCEAN = registerBiome(44, "warm_ocean"sv, BiomeMaker::makeWarmOceanBiome());
    LUKEWARM_OCEAN = registerBiome(45, "lukewarm_ocean"sv, BiomeMaker::makeLukewarmOceanBiome(false));
    COLD_OCEAN = registerBiome(46, "cold_ocean"sv, BiomeMaker::makeColdOceanBiome(false));
    DEEP_WARM_OCEAN = registerBiome(47, "deep_warm_ocean"sv,  BiomeMaker::makeDeepWarmOceanBiome());
    DEEP_LUKEWARM_OCEAN = registerBiome(48, "deep_lukewarm_ocean"sv, BiomeMaker::makeLukewarmOceanBiome(true));
    DEEP_COLD_OCEAN = registerBiome(49, "deep_cold_ocean"sv, BiomeMaker::makeColdOceanBiome(true));
    DEEP_FROZEN_OCEAN = registerBiome(50, "deep_frozen_ocean"sv, BiomeMaker::makeFrozenOceanBiome(true));
    THE_VOID = registerBiome(127, "the_void"sv, BiomeMaker::makeVoidBiome());
    SUNFLOWER_PLAINS = registerBiome(129, "sunflower_plains"sv, BiomeMaker::makePlainsBiome(true));
    DESERT_LAKES = registerBiome(130, "desert_lakes"sv, BiomeMaker::makeDesertBiome(0.225F, 0.25F, false, false, false));
    GRAVELLY_MOUNTAINS = registerBiome(131, "gravelly_mountains"sv, BiomeMaker::makeMountainBiome(1.0F, 0.5F, ConfiguredSurfaceBuilders::GRAVELLY_MOUNTAIN, false));
    FLOWER_FOREST = registerBiome(132, "flower_forest"sv, BiomeMaker::makeFlowerForestBiome());
    TAIGA_MOUNTAINS = registerBiome(133, "taiga_mountains"sv, BiomeMaker::makeTaigaBiome(0.3F, 0.4F, false, true, false, false));
    SWAMP_HILLS = registerBiome(134, "swamp_hills"sv, BiomeMaker::makeGenericSwampBiome(-0.1F, 0.3F, true));
    ICE_SPIKES = registerBiome(140, "ice_spikes"sv, BiomeMaker::makeSnowyBiome(0.425F, 0.45000002F, true, false));
    MODIFIED_JUNGLE = registerBiome(149, "modified_jungle"sv, BiomeMaker::makeModifiedJungleBiome());
    MODIFIED_JUNGLE_EDGE = registerBiome(151, "modified_jungle_edge"sv, BiomeMaker::makeModifiedJungleEdgeBiome());
    TALL_BIRCH_FOREST = registerBiome(155, "tall_birch_forest"sv, BiomeMaker::makeBirchForestBiome(0.2F, 0.4F, true));
    TALL_BIRCH_HILLS = registerBiome(156, "tall_birch_hills"sv, BiomeMaker::makeBirchForestBiome(0.55F, 0.5F, true));
    DARK_FOREST_HILLS = registerBiome(157, "dark_forest_hills"sv, BiomeMaker::makeDarkForestBiome(0.2F, 0.4F, true));
    SNOWY_TAIGA_MOUNTAINS = registerBiome(158, "snowy_taiga_mountains"sv, BiomeMaker::makeTaigaBiome(0.3F, 0.4F, true, true, false, false));
    GIANT_SPRUCE_TAIGA = registerBiome(160, "giant_spruce_taiga"sv, BiomeMaker::makeGiantTaigaBiome(0.2F, 0.2F, 0.25F, true));
    GIANT_SPRUCE_TAIGA_HILLS = registerBiome(161, "giant_spruce_taiga_hills"sv, BiomeMaker::makeGiantTaigaBiome(0.2F, 0.2F, 0.25F, true));
    MODIFIED_GRAVELLY_MOUNTAINS = registerBiome(162, "modified_gravelly_mountains"sv, BiomeMaker::makeMountainBiome(1.0, 0.5, ConfiguredSurfaceBuilders::GRAVELLY_MOUNTAIN, false));
    SHATTERED_SAVANNA = registerBiome(163, "shattered_savanna"sv, BiomeMaker::makeSavannaBiome(0.3625F, 1.225F, 1.1F, true, true));
    SHATTERED_SAVANNA_PLATEAU = registerBiome(164, "shattered_savanna_plateau"sv, BiomeMaker::makeSavannaBiome(1.05F, 1.2125001F, 1.0F, true, true));
    ERODED_BADLANDS = registerBiome(165, "eroded_badlands"sv, BiomeMaker::makeErodedBadlandsBiome());
    MODIFIED_WOODED_BADLANDS_PLATEAU = registerBiome(166, "modified_wooded_badlands_plateau"sv, BiomeMaker::makeWoodedBadlandsPlateauBiome(0.45, 0.3));
    MODIFIED_BADLANDS_PLATEAU = registerBiome(167, "modified_badlands_plateau"sv, BiomeMaker::makeBadlandsBiome(0.45, 0.3, true));
    BAMBOO_JUNGLE = registerBiome(168, "bamboo_jungle"sv, BiomeMaker::makeBambooJungleBiome());
    BAMBOO_JUNGLE_HILLS = registerBiome(169, "bamboo_jungle_hills"sv, BiomeMaker::makeBambooJungleHillsBiome());
    SOUL_SAND_VALLEY = registerBiome(170, "soul_sand_valley"sv, BiomeMaker::makeSoulSandValleyBiome());
    CRIMSON_FOREST = registerBiome(171, "crimson_forest"sv, BiomeMaker::makeCrimsonForestBiome());
    WARPED_FOREST = registerBiome(172, "warped_forest"sv, BiomeMaker::makeWarpedForestBiome());
    BASALT_DELTAS = registerBiome(173, "basalt_deltas"sv, BiomeMaker::makeBasaltDeltasBiome());
}