#include "States.hpp"

#include "Block.hpp"
#include "Blocks.hpp"
#include "BlockData.hpp"

BlockData States::AIR;
BlockData States::STONE;
BlockData States::GRANITE;
BlockData States::POLISHED_GRANITE;
BlockData States::DIORITE;
BlockData States::POLISHED_DIORITE;
BlockData States::ANDESITE;
BlockData States::POLISHED_ANDESITE;
BlockData States::GRASS_BLOCK;
BlockData States::DIRT;
BlockData States::COARSE_DIRT;
BlockData States::PODZOL;
BlockData States::COBBLESTONE;
BlockData States::OAK_PLANKS;
BlockData States::SPRUCE_PLANKS;
BlockData States::BIRCH_PLANKS;
BlockData States::JUNGLE_PLANKS;
BlockData States::ACACIA_PLANKS;
BlockData States::DARK_OAK_PLANKS;
BlockData States::OAK_SAPLING;
BlockData States::SPRUCE_SAPLING;
BlockData States::BIRCH_SAPLING;
BlockData States::JUNGLE_SAPLING;
BlockData States::ACACIA_SAPLING;
BlockData States::DARK_OAK_SAPLING;
BlockData States::BEDROCK;
BlockData States::WATER;
BlockData States::LAVA;
BlockData States::SAND;
BlockData States::RED_SAND;
BlockData States::GRAVEL;
BlockData States::GOLD_ORE;
BlockData States::IRON_ORE;
BlockData States::COAL_ORE;
BlockData States::NETHER_GOLD_ORE;
BlockData States::OAK_LOG;
BlockData States::SPRUCE_LOG;
BlockData States::BIRCH_LOG;
BlockData States::JUNGLE_LOG;
BlockData States::ACACIA_LOG;
BlockData States::DARK_OAK_LOG;
BlockData States::STRIPPED_SPRUCE_LOG;
BlockData States::STRIPPED_BIRCH_LOG;
BlockData States::STRIPPED_JUNGLE_LOG;
BlockData States::STRIPPED_ACACIA_LOG;
BlockData States::STRIPPED_DARK_OAK_LOG;
BlockData States::STRIPPED_OAK_LOG;
BlockData States::OAK_WOOD;
BlockData States::SPRUCE_WOOD;
BlockData States::BIRCH_WOOD;
BlockData States::JUNGLE_WOOD;
BlockData States::ACACIA_WOOD;
BlockData States::DARK_OAK_WOOD;
BlockData States::STRIPPED_OAK_WOOD;
BlockData States::STRIPPED_SPRUCE_WOOD;
BlockData States::STRIPPED_BIRCH_WOOD;
BlockData States::STRIPPED_JUNGLE_WOOD;
BlockData States::STRIPPED_ACACIA_WOOD;
BlockData States::STRIPPED_DARK_OAK_WOOD;
BlockData States::OAK_LEAVES;
BlockData States::SPRUCE_LEAVES;
BlockData States::BIRCH_LEAVES;
BlockData States::JUNGLE_LEAVES;
BlockData States::ACACIA_LEAVES;
BlockData States::DARK_OAK_LEAVES;
BlockData States::SPONGE;
BlockData States::WET_SPONGE;
BlockData States::GLASS;
BlockData States::LAPIS_ORE;
BlockData States::LAPIS_BLOCK;
BlockData States::DISPENSER;
BlockData States::SANDSTONE;
BlockData States::CHISELED_SANDSTONE;
BlockData States::CUT_SANDSTONE;
BlockData States::NOTE_BLOCK;
BlockData States::WHITE_BED;
BlockData States::ORANGE_BED;
BlockData States::MAGENTA_BED;
BlockData States::LIGHT_BLUE_BED;
BlockData States::YELLOW_BED;
BlockData States::LIME_BED;
BlockData States::PINK_BED;
BlockData States::GRAY_BED;
BlockData States::LIGHT_GRAY_BED;
BlockData States::CYAN_BED;
BlockData States::PURPLE_BED;
BlockData States::BLUE_BED;
BlockData States::BROWN_BED;
BlockData States::GREEN_BED;
BlockData States::RED_BED;
BlockData States::BLACK_BED;
BlockData States::POWERED_RAIL;
BlockData States::DETECTOR_RAIL;
BlockData States::STICKY_PISTON;
BlockData States::COBWEB;
BlockData States::GRASS;
BlockData States::FERN;
BlockData States::DEAD_BUSH;
BlockData States::SEAGRASS;
BlockData States::TALL_SEAGRASS;
BlockData States::PISTON;
BlockData States::PISTON_HEAD;
BlockData States::WHITE_WOOL;
BlockData States::ORANGE_WOOL;
BlockData States::MAGENTA_WOOL;
BlockData States::LIGHT_BLUE_WOOL;
BlockData States::YELLOW_WOOL;
BlockData States::LIME_WOOL;
BlockData States::PINK_WOOL;
BlockData States::GRAY_WOOL;
BlockData States::LIGHT_GRAY_WOOL;
BlockData States::CYAN_WOOL;
BlockData States::PURPLE_WOOL;
BlockData States::BLUE_WOOL;
BlockData States::BROWN_WOOL;
BlockData States::GREEN_WOOL;
BlockData States::RED_WOOL;
BlockData States::BLACK_WOOL;
BlockData States::MOVING_PISTON;
BlockData States::DANDELION;
BlockData States::POPPY;
BlockData States::BLUE_ORCHID;
BlockData States::ALLIUM;
BlockData States::AZURE_BLUET;
BlockData States::RED_TULIP;
BlockData States::ORANGE_TULIP;
BlockData States::WHITE_TULIP;
BlockData States::PINK_TULIP;
BlockData States::OXEYE_DAISY;
BlockData States::CORNFLOWER;
BlockData States::WITHER_ROSE;
BlockData States::LILY_OF_THE_VALLEY;
BlockData States::BROWN_MUSHROOM;
BlockData States::RED_MUSHROOM;
BlockData States::GOLD_BLOCK;
BlockData States::IRON_BLOCK;
BlockData States::BRICKS;
BlockData States::TNT;
BlockData States::BOOKSHELF;
BlockData States::MOSSY_COBBLESTONE;
BlockData States::OBSIDIAN;
BlockData States::TORCH;
BlockData States::WALL_TORCH;
BlockData States::FIRE;
BlockData States::SOUL_FIRE;
BlockData States::SPAWNER;
BlockData States::OAK_STAIRS;
BlockData States::CHEST;
BlockData States::REDSTONE_WIRE;
BlockData States::DIAMOND_ORE;
BlockData States::DIAMOND_BLOCK;
BlockData States::CRAFTING_TABLE;
BlockData States::WHEAT;
BlockData States::FARMLAND;
BlockData States::FURNACE;
BlockData States::OAK_SIGN;
BlockData States::SPRUCE_SIGN;
BlockData States::BIRCH_SIGN;
BlockData States::ACACIA_SIGN;
BlockData States::JUNGLE_SIGN;
BlockData States::DARK_OAK_SIGN;
BlockData States::OAK_DOOR;
BlockData States::LADDER;
BlockData States::RAIL;
BlockData States::COBBLESTONE_STAIRS;
BlockData States::OAK_WALL_SIGN;
BlockData States::SPRUCE_WALL_SIGN;
BlockData States::BIRCH_WALL_SIGN;
BlockData States::ACACIA_WALL_SIGN;
BlockData States::JUNGLE_WALL_SIGN;
BlockData States::DARK_OAK_WALL_SIGN;
BlockData States::LEVER;
BlockData States::STONE_PRESSURE_PLATE;
BlockData States::IRON_DOOR;
BlockData States::OAK_PRESSURE_PLATE;
BlockData States::SPRUCE_PRESSURE_PLATE;
BlockData States::BIRCH_PRESSURE_PLATE;
BlockData States::JUNGLE_PRESSURE_PLATE;
BlockData States::ACACIA_PRESSURE_PLATE;
BlockData States::DARK_OAK_PRESSURE_PLATE;
BlockData States::REDSTONE_ORE;
BlockData States::REDSTONE_TORCH;
BlockData States::REDSTONE_WALL_TORCH;
BlockData States::STONE_BUTTON;
BlockData States::SNOW;
BlockData States::ICE;
BlockData States::SNOW_BLOCK;
BlockData States::CACTUS;
BlockData States::CLAY;
BlockData States::SUGAR_CANE;
BlockData States::JUKEBOX;
BlockData States::OAK_FENCE;
BlockData States::PUMPKIN;
BlockData States::NETHERRACK;
BlockData States::SOUL_SAND;
BlockData States::SOUL_SOIL;
BlockData States::BASALT;
BlockData States::POLISHED_BASALT;
BlockData States::SOUL_TORCH;
BlockData States::SOUL_WALL_TORCH;
BlockData States::GLOWSTONE;
BlockData States::NETHER_PORTAL;
BlockData States::CARVED_PUMPKIN;
BlockData States::JACK_O_LANTERN;
BlockData States::CAKE;
BlockData States::REPEATER;
BlockData States::WHITE_STAINED_GLASS;
BlockData States::ORANGE_STAINED_GLASS;
BlockData States::MAGENTA_STAINED_GLASS;
BlockData States::LIGHT_BLUE_STAINED_GLASS;
BlockData States::YELLOW_STAINED_GLASS;
BlockData States::LIME_STAINED_GLASS;
BlockData States::PINK_STAINED_GLASS;
BlockData States::GRAY_STAINED_GLASS;
BlockData States::LIGHT_GRAY_STAINED_GLASS;
BlockData States::CYAN_STAINED_GLASS;
BlockData States::PURPLE_STAINED_GLASS;
BlockData States::BLUE_STAINED_GLASS;
BlockData States::BROWN_STAINED_GLASS;
BlockData States::GREEN_STAINED_GLASS;
BlockData States::RED_STAINED_GLASS;
BlockData States::BLACK_STAINED_GLASS;
BlockData States::OAK_TRAPDOOR;
BlockData States::SPRUCE_TRAPDOOR;
BlockData States::BIRCH_TRAPDOOR;
BlockData States::JUNGLE_TRAPDOOR;
BlockData States::ACACIA_TRAPDOOR;
BlockData States::DARK_OAK_TRAPDOOR;
BlockData States::STONE_BRICKS;
BlockData States::MOSSY_STONE_BRICKS;
BlockData States::CRACKED_STONE_BRICKS;
BlockData States::CHISELED_STONE_BRICKS;
BlockData States::INFESTED_STONE;
BlockData States::INFESTED_COBBLESTONE;
BlockData States::INFESTED_STONE_BRICKS;
BlockData States::INFESTED_MOSSY_STONE_BRICKS;
BlockData States::INFESTED_CRACKED_STONE_BRICKS;
BlockData States::INFESTED_CHISELED_STONE_BRICKS;
BlockData States::BROWN_MUSHROOM_BLOCK;
BlockData States::RED_MUSHROOM_BLOCK;
BlockData States::MUSHROOM_STEM;
BlockData States::IRON_BARS;
BlockData States::CHAIN;
BlockData States::GLASS_PANE;
BlockData States::MELON;
BlockData States::ATTACHED_PUMPKIN_STEM;
BlockData States::ATTACHED_MELON_STEM;
BlockData States::PUMPKIN_STEM;
BlockData States::MELON_STEM;
BlockData States::VINE;
BlockData States::OAK_FENCE_GATE;
BlockData States::BRICK_STAIRS;
BlockData States::STONE_BRICK_STAIRS;
BlockData States::MYCELIUM;
BlockData States::LILY_PAD;
BlockData States::NETHER_BRICKS;
BlockData States::NETHER_BRICK_FENCE;
BlockData States::NETHER_BRICK_STAIRS;
BlockData States::NETHER_WART;
BlockData States::ENCHANTING_TABLE;
BlockData States::BREWING_STAND;
BlockData States::CAULDRON;
BlockData States::END_PORTAL;
BlockData States::END_PORTAL_FRAME;
BlockData States::END_STONE;
BlockData States::DRAGON_EGG;
BlockData States::REDSTONE_LAMP;
BlockData States::COCOA;
BlockData States::SANDSTONE_STAIRS;
BlockData States::EMERALD_ORE;
BlockData States::ENDER_CHEST;
BlockData States::TRIPWIRE_HOOK;
BlockData States::TRIPWIRE;
BlockData States::EMERALD_BLOCK;
BlockData States::SPRUCE_STAIRS;
BlockData States::BIRCH_STAIRS;
BlockData States::JUNGLE_STAIRS;
BlockData States::COMMAND_BLOCK;
BlockData States::BEACON;
BlockData States::COBBLESTONE_WALL;
BlockData States::MOSSY_COBBLESTONE_WALL;
BlockData States::FLOWER_POT;
BlockData States::POTTED_OAK_SAPLING;
BlockData States::POTTED_SPRUCE_SAPLING;
BlockData States::POTTED_BIRCH_SAPLING;
BlockData States::POTTED_JUNGLE_SAPLING;
BlockData States::POTTED_ACACIA_SAPLING;
BlockData States::POTTED_DARK_OAK_SAPLING;
BlockData States::POTTED_FERN;
BlockData States::POTTED_DANDELION;
BlockData States::POTTED_POPPY;
BlockData States::POTTED_BLUE_ORCHID;
BlockData States::POTTED_ALLIUM;
BlockData States::POTTED_AZURE_BLUET;
BlockData States::POTTED_RED_TULIP;
BlockData States::POTTED_ORANGE_TULIP;
BlockData States::POTTED_WHITE_TULIP;
BlockData States::POTTED_PINK_TULIP;
BlockData States::POTTED_OXEYE_DAISY;
BlockData States::POTTED_CORNFLOWER;
BlockData States::POTTED_LILY_OF_THE_VALLEY;
BlockData States::POTTED_WITHER_ROSE;
BlockData States::POTTED_RED_MUSHROOM;
BlockData States::POTTED_BROWN_MUSHROOM;
BlockData States::POTTED_DEAD_BUSH;
BlockData States::POTTED_CACTUS;
BlockData States::CARROTS;
BlockData States::POTATOES;
BlockData States::OAK_BUTTON;
BlockData States::SPRUCE_BUTTON;
BlockData States::BIRCH_BUTTON;
BlockData States::JUNGLE_BUTTON;
BlockData States::ACACIA_BUTTON;
BlockData States::DARK_OAK_BUTTON;
BlockData States::SKELETON_SKULL;
BlockData States::SKELETON_WALL_SKULL;
BlockData States::WITHER_SKELETON_SKULL;
BlockData States::WITHER_SKELETON_WALL_SKULL;
BlockData States::ZOMBIE_HEAD;
BlockData States::ZOMBIE_WALL_HEAD;
BlockData States::PLAYER_HEAD;
BlockData States::PLAYER_WALL_HEAD;
BlockData States::CREEPER_HEAD;
BlockData States::CREEPER_WALL_HEAD;
BlockData States::DRAGON_HEAD;
BlockData States::DRAGON_WALL_HEAD;
BlockData States::ANVIL;
BlockData States::CHIPPED_ANVIL;
BlockData States::DAMAGED_ANVIL;
BlockData States::TRAPPED_CHEST;
BlockData States::LIGHT_WEIGHTED_PRESSURE_PLATE;
BlockData States::HEAVY_WEIGHTED_PRESSURE_PLATE;
BlockData States::COMPARATOR;
BlockData States::DAYLIGHT_DETECTOR;
BlockData States::REDSTONE_BLOCK;
BlockData States::NETHER_QUARTZ_ORE;
BlockData States::HOPPER;
BlockData States::QUARTZ_BLOCK;
BlockData States::CHISELED_QUARTZ_BLOCK;
BlockData States::QUARTZ_PILLAR;
BlockData States::QUARTZ_STAIRS;
BlockData States::ACTIVATOR_RAIL;
BlockData States::DROPPER;
BlockData States::WHITE_TERRACOTTA;
BlockData States::ORANGE_TERRACOTTA;
BlockData States::MAGENTA_TERRACOTTA;
BlockData States::LIGHT_BLUE_TERRACOTTA;
BlockData States::YELLOW_TERRACOTTA;
BlockData States::LIME_TERRACOTTA;
BlockData States::PINK_TERRACOTTA;
BlockData States::GRAY_TERRACOTTA;
BlockData States::LIGHT_GRAY_TERRACOTTA;
BlockData States::CYAN_TERRACOTTA;
BlockData States::PURPLE_TERRACOTTA;
BlockData States::BLUE_TERRACOTTA;
BlockData States::BROWN_TERRACOTTA;
BlockData States::GREEN_TERRACOTTA;
BlockData States::RED_TERRACOTTA;
BlockData States::BLACK_TERRACOTTA;
BlockData States::WHITE_STAINED_GLASS_PANE;
BlockData States::ORANGE_STAINED_GLASS_PANE;
BlockData States::MAGENTA_STAINED_GLASS_PANE;
BlockData States::LIGHT_BLUE_STAINED_GLASS_PANE;
BlockData States::YELLOW_STAINED_GLASS_PANE;
BlockData States::LIME_STAINED_GLASS_PANE;
BlockData States::PINK_STAINED_GLASS_PANE;
BlockData States::GRAY_STAINED_GLASS_PANE;
BlockData States::LIGHT_GRAY_STAINED_GLASS_PANE;
BlockData States::CYAN_STAINED_GLASS_PANE;
BlockData States::PURPLE_STAINED_GLASS_PANE;
BlockData States::BLUE_STAINED_GLASS_PANE;
BlockData States::BROWN_STAINED_GLASS_PANE;
BlockData States::GREEN_STAINED_GLASS_PANE;
BlockData States::RED_STAINED_GLASS_PANE;
BlockData States::BLACK_STAINED_GLASS_PANE;
BlockData States::ACACIA_STAIRS;
BlockData States::DARK_OAK_STAIRS;
BlockData States::SLIME_BLOCK;
BlockData States::BARRIER;
BlockData States::IRON_TRAPDOOR;
BlockData States::PRISMARINE;
BlockData States::PRISMARINE_BRICKS;
BlockData States::DARK_PRISMARINE;
BlockData States::PRISMARINE_STAIRS;
BlockData States::PRISMARINE_BRICK_STAIRS;
BlockData States::DARK_PRISMARINE_STAIRS;
BlockData States::PRISMARINE_SLAB;
BlockData States::PRISMARINE_BRICK_SLAB;
BlockData States::DARK_PRISMARINE_SLAB;
BlockData States::SEA_LANTERN;
BlockData States::HAY_BLOCK;
BlockData States::WHITE_CARPET;
BlockData States::ORANGE_CARPET;
BlockData States::MAGENTA_CARPET;
BlockData States::LIGHT_BLUE_CARPET;
BlockData States::YELLOW_CARPET;
BlockData States::LIME_CARPET;
BlockData States::PINK_CARPET;
BlockData States::GRAY_CARPET;
BlockData States::LIGHT_GRAY_CARPET;
BlockData States::CYAN_CARPET;
BlockData States::PURPLE_CARPET;
BlockData States::BLUE_CARPET;
BlockData States::BROWN_CARPET;
BlockData States::GREEN_CARPET;
BlockData States::RED_CARPET;
BlockData States::BLACK_CARPET;
BlockData States::TERRACOTTA;
BlockData States::COAL_BLOCK;
BlockData States::PACKED_ICE;
BlockData States::SUNFLOWER;
BlockData States::LILAC;
BlockData States::ROSE_BUSH;
BlockData States::PEONY;
BlockData States::TALL_GRASS;
BlockData States::LARGE_FERN;
BlockData States::WHITE_BANNER;
BlockData States::ORANGE_BANNER;
BlockData States::MAGENTA_BANNER;
BlockData States::LIGHT_BLUE_BANNER;
BlockData States::YELLOW_BANNER;
BlockData States::LIME_BANNER;
BlockData States::PINK_BANNER;
BlockData States::GRAY_BANNER;
BlockData States::LIGHT_GRAY_BANNER;
BlockData States::CYAN_BANNER;
BlockData States::PURPLE_BANNER;
BlockData States::BLUE_BANNER;
BlockData States::BROWN_BANNER;
BlockData States::GREEN_BANNER;
BlockData States::RED_BANNER;
BlockData States::BLACK_BANNER;
BlockData States::WHITE_WALL_BANNER;
BlockData States::ORANGE_WALL_BANNER;
BlockData States::MAGENTA_WALL_BANNER;
BlockData States::LIGHT_BLUE_WALL_BANNER;
BlockData States::YELLOW_WALL_BANNER;
BlockData States::LIME_WALL_BANNER;
BlockData States::PINK_WALL_BANNER;
BlockData States::GRAY_WALL_BANNER;
BlockData States::LIGHT_GRAY_WALL_BANNER;
BlockData States::CYAN_WALL_BANNER;
BlockData States::PURPLE_WALL_BANNER;
BlockData States::BLUE_WALL_BANNER;
BlockData States::BROWN_WALL_BANNER;
BlockData States::GREEN_WALL_BANNER;
BlockData States::RED_WALL_BANNER;
BlockData States::BLACK_WALL_BANNER;
BlockData States::RED_SANDSTONE;
BlockData States::CHISELED_RED_SANDSTONE;
BlockData States::CUT_RED_SANDSTONE;
BlockData States::RED_SANDSTONE_STAIRS;
BlockData States::OAK_SLAB;
BlockData States::SPRUCE_SLAB;
BlockData States::BIRCH_SLAB;
BlockData States::JUNGLE_SLAB;
BlockData States::ACACIA_SLAB;
BlockData States::DARK_OAK_SLAB;
BlockData States::STONE_SLAB;
BlockData States::SMOOTH_STONE_SLAB;
BlockData States::SANDSTONE_SLAB;
BlockData States::CUT_SANDSTONE_SLAB;
BlockData States::PETRIFIED_OAK_SLAB;
BlockData States::COBBLESTONE_SLAB;
BlockData States::BRICK_SLAB;
BlockData States::STONE_BRICK_SLAB;
BlockData States::NETHER_BRICK_SLAB;
BlockData States::QUARTZ_SLAB;
BlockData States::RED_SANDSTONE_SLAB;
BlockData States::CUT_RED_SANDSTONE_SLAB;
BlockData States::PURPUR_SLAB;
BlockData States::SMOOTH_STONE;
BlockData States::SMOOTH_SANDSTONE;
BlockData States::SMOOTH_QUARTZ;
BlockData States::SMOOTH_RED_SANDSTONE;
BlockData States::SPRUCE_FENCE_GATE;
BlockData States::BIRCH_FENCE_GATE;
BlockData States::JUNGLE_FENCE_GATE;
BlockData States::ACACIA_FENCE_GATE;
BlockData States::DARK_OAK_FENCE_GATE;
BlockData States::SPRUCE_FENCE;
BlockData States::BIRCH_FENCE;
BlockData States::JUNGLE_FENCE;
BlockData States::ACACIA_FENCE;
BlockData States::DARK_OAK_FENCE;
BlockData States::SPRUCE_DOOR;
BlockData States::BIRCH_DOOR;
BlockData States::JUNGLE_DOOR;
BlockData States::ACACIA_DOOR;
BlockData States::DARK_OAK_DOOR;
BlockData States::END_ROD;
BlockData States::CHORUS_PLANT;
BlockData States::CHORUS_FLOWER;
BlockData States::PURPUR_BLOCK;
BlockData States::PURPUR_PILLAR;
BlockData States::PURPUR_STAIRS;
BlockData States::END_STONE_BRICKS;
BlockData States::BEETROOTS;
BlockData States::GRASS_PATH;
BlockData States::END_GATEWAY;
BlockData States::REPEATING_COMMAND_BLOCK;
BlockData States::CHAIN_COMMAND_BLOCK;
BlockData States::FROSTED_ICE;
BlockData States::MAGMA_BLOCK;
BlockData States::NETHER_WART_BLOCK;
BlockData States::RED_NETHER_BRICKS;
BlockData States::BONE_BLOCK;
BlockData States::STRUCTURE_VOID;
BlockData States::OBSERVER;
BlockData States::SHULKER_BOX;
BlockData States::WHITE_SHULKER_BOX;
BlockData States::ORANGE_SHULKER_BOX;
BlockData States::MAGENTA_SHULKER_BOX;
BlockData States::LIGHT_BLUE_SHULKER_BOX;
BlockData States::YELLOW_SHULKER_BOX;
BlockData States::LIME_SHULKER_BOX;
BlockData States::PINK_SHULKER_BOX;
BlockData States::GRAY_SHULKER_BOX;
BlockData States::LIGHT_GRAY_SHULKER_BOX;
BlockData States::CYAN_SHULKER_BOX;
BlockData States::PURPLE_SHULKER_BOX;
BlockData States::BLUE_SHULKER_BOX;
BlockData States::BROWN_SHULKER_BOX;
BlockData States::GREEN_SHULKER_BOX;
BlockData States::RED_SHULKER_BOX;
BlockData States::BLACK_SHULKER_BOX;
BlockData States::WHITE_GLAZED_TERRACOTTA;
BlockData States::ORANGE_GLAZED_TERRACOTTA;
BlockData States::MAGENTA_GLAZED_TERRACOTTA;
BlockData States::LIGHT_BLUE_GLAZED_TERRACOTTA;
BlockData States::YELLOW_GLAZED_TERRACOTTA;
BlockData States::LIME_GLAZED_TERRACOTTA;
BlockData States::PINK_GLAZED_TERRACOTTA;
BlockData States::GRAY_GLAZED_TERRACOTTA;
BlockData States::LIGHT_GRAY_GLAZED_TERRACOTTA;
BlockData States::CYAN_GLAZED_TERRACOTTA;
BlockData States::PURPLE_GLAZED_TERRACOTTA;
BlockData States::BLUE_GLAZED_TERRACOTTA;
BlockData States::BROWN_GLAZED_TERRACOTTA;
BlockData States::GREEN_GLAZED_TERRACOTTA;
BlockData States::RED_GLAZED_TERRACOTTA;
BlockData States::BLACK_GLAZED_TERRACOTTA;
BlockData States::WHITE_CONCRETE;
BlockData States::ORANGE_CONCRETE;
BlockData States::MAGENTA_CONCRETE;
BlockData States::LIGHT_BLUE_CONCRETE;
BlockData States::YELLOW_CONCRETE;
BlockData States::LIME_CONCRETE;
BlockData States::PINK_CONCRETE;
BlockData States::GRAY_CONCRETE;
BlockData States::LIGHT_GRAY_CONCRETE;
BlockData States::CYAN_CONCRETE;
BlockData States::PURPLE_CONCRETE;
BlockData States::BLUE_CONCRETE;
BlockData States::BROWN_CONCRETE;
BlockData States::GREEN_CONCRETE;
BlockData States::RED_CONCRETE;
BlockData States::BLACK_CONCRETE;
BlockData States::WHITE_CONCRETE_POWDER;
BlockData States::ORANGE_CONCRETE_POWDER;
BlockData States::MAGENTA_CONCRETE_POWDER;
BlockData States::LIGHT_BLUE_CONCRETE_POWDER;
BlockData States::YELLOW_CONCRETE_POWDER;
BlockData States::LIME_CONCRETE_POWDER;
BlockData States::PINK_CONCRETE_POWDER;
BlockData States::GRAY_CONCRETE_POWDER;
BlockData States::LIGHT_GRAY_CONCRETE_POWDER;
BlockData States::CYAN_CONCRETE_POWDER;
BlockData States::PURPLE_CONCRETE_POWDER;
BlockData States::BLUE_CONCRETE_POWDER;
BlockData States::BROWN_CONCRETE_POWDER;
BlockData States::GREEN_CONCRETE_POWDER;
BlockData States::RED_CONCRETE_POWDER;
BlockData States::BLACK_CONCRETE_POWDER;
BlockData States::KELP;
BlockData States::KELP_PLANT;
BlockData States::DRIED_KELP_BLOCK;
BlockData States::TURTLE_EGG;
BlockData States::DEAD_TUBE_CORAL_BLOCK;
BlockData States::DEAD_BRAIN_CORAL_BLOCK;
BlockData States::DEAD_BUBBLE_CORAL_BLOCK;
BlockData States::DEAD_FIRE_CORAL_BLOCK;
BlockData States::DEAD_HORN_CORAL_BLOCK;
BlockData States::TUBE_CORAL_BLOCK;
BlockData States::BRAIN_CORAL_BLOCK;
BlockData States::BUBBLE_CORAL_BLOCK;
BlockData States::FIRE_CORAL_BLOCK;
BlockData States::HORN_CORAL_BLOCK;
BlockData States::DEAD_TUBE_CORAL;
BlockData States::DEAD_BRAIN_CORAL;
BlockData States::DEAD_BUBBLE_CORAL;
BlockData States::DEAD_FIRE_CORAL;
BlockData States::DEAD_HORN_CORAL;
BlockData States::TUBE_CORAL;
BlockData States::BRAIN_CORAL;
BlockData States::BUBBLE_CORAL;
BlockData States::FIRE_CORAL;
BlockData States::HORN_CORAL;
BlockData States::DEAD_TUBE_CORAL_FAN;
BlockData States::DEAD_BRAIN_CORAL_FAN;
BlockData States::DEAD_BUBBLE_CORAL_FAN;
BlockData States::DEAD_FIRE_CORAL_FAN;
BlockData States::DEAD_HORN_CORAL_FAN;
BlockData States::TUBE_CORAL_FAN;
BlockData States::BRAIN_CORAL_FAN;
BlockData States::BUBBLE_CORAL_FAN;
BlockData States::FIRE_CORAL_FAN;
BlockData States::HORN_CORAL_FAN;
BlockData States::DEAD_TUBE_CORAL_WALL_FAN;
BlockData States::DEAD_BRAIN_CORAL_WALL_FAN;
BlockData States::DEAD_BUBBLE_CORAL_WALL_FAN;
BlockData States::DEAD_FIRE_CORAL_WALL_FAN;
BlockData States::DEAD_HORN_CORAL_WALL_FAN;
BlockData States::TUBE_CORAL_WALL_FAN;
BlockData States::BRAIN_CORAL_WALL_FAN;
BlockData States::BUBBLE_CORAL_WALL_FAN;
BlockData States::FIRE_CORAL_WALL_FAN;
BlockData States::HORN_CORAL_WALL_FAN;
BlockData States::SEA_PICKLE;
BlockData States::BLUE_ICE;
BlockData States::CONDUIT;
BlockData States::BAMBOO_SAPLING;
BlockData States::BAMBOO;
BlockData States::POTTED_BAMBOO;
BlockData States::VOID_AIR;
BlockData States::CAVE_AIR;
BlockData States::BUBBLE_COLUMN;
BlockData States::POLISHED_GRANITE_STAIRS;
BlockData States::SMOOTH_RED_SANDSTONE_STAIRS;
BlockData States::MOSSY_STONE_BRICK_STAIRS;
BlockData States::POLISHED_DIORITE_STAIRS;
BlockData States::MOSSY_COBBLESTONE_STAIRS;
BlockData States::END_STONE_BRICK_STAIRS;
BlockData States::STONE_STAIRS;
BlockData States::SMOOTH_SANDSTONE_STAIRS;
BlockData States::SMOOTH_QUARTZ_STAIRS;
BlockData States::GRANITE_STAIRS;
BlockData States::ANDESITE_STAIRS;
BlockData States::RED_NETHER_BRICK_STAIRS;
BlockData States::POLISHED_ANDESITE_STAIRS;
BlockData States::DIORITE_STAIRS;
BlockData States::POLISHED_GRANITE_SLAB;
BlockData States::SMOOTH_RED_SANDSTONE_SLAB;
BlockData States::MOSSY_STONE_BRICK_SLAB;
BlockData States::POLISHED_DIORITE_SLAB;
BlockData States::MOSSY_COBBLESTONE_SLAB;
BlockData States::END_STONE_BRICK_SLAB;
BlockData States::SMOOTH_SANDSTONE_SLAB;
BlockData States::SMOOTH_QUARTZ_SLAB;
BlockData States::GRANITE_SLAB;
BlockData States::ANDESITE_SLAB;
BlockData States::RED_NETHER_BRICK_SLAB;
BlockData States::POLISHED_ANDESITE_SLAB;
BlockData States::DIORITE_SLAB;
BlockData States::BRICK_WALL;
BlockData States::PRISMARINE_WALL;
BlockData States::RED_SANDSTONE_WALL;
BlockData States::MOSSY_STONE_BRICK_WALL;
BlockData States::GRANITE_WALL;
BlockData States::STONE_BRICK_WALL;
BlockData States::NETHER_BRICK_WALL;
BlockData States::ANDESITE_WALL;
BlockData States::RED_NETHER_BRICK_WALL;
BlockData States::SANDSTONE_WALL;
BlockData States::END_STONE_BRICK_WALL;
BlockData States::DIORITE_WALL;
BlockData States::SCAFFOLDING;
BlockData States::LOOM;
BlockData States::BARREL;
BlockData States::SMOKER;
BlockData States::BLAST_FURNACE;
BlockData States::CARTOGRAPHY_TABLE;
BlockData States::FLETCHING_TABLE;
BlockData States::GRINDSTONE;
BlockData States::LECTERN;
BlockData States::SMITHING_TABLE;
BlockData States::STONECUTTER;
BlockData States::BELL;
BlockData States::LANTERN;
BlockData States::SOUL_LANTERN;
BlockData States::CAMPFIRE;
BlockData States::SOUL_CAMPFIRE;
BlockData States::SWEET_BERRY_BUSH;
BlockData States::WARPED_STEM;
BlockData States::STRIPPED_WARPED_STEM;
BlockData States::WARPED_HYPHAE;
BlockData States::STRIPPED_WARPED_HYPHAE;
BlockData States::WARPED_NYLIUM;
BlockData States::WARPED_FUNGUS;
BlockData States::WARPED_WART_BLOCK;
BlockData States::WARPED_ROOTS;
BlockData States::NETHER_SPROUTS;
BlockData States::CRIMSON_STEM;
BlockData States::STRIPPED_CRIMSON_STEM;
BlockData States::CRIMSON_HYPHAE;
BlockData States::STRIPPED_CRIMSON_HYPHAE;
BlockData States::CRIMSON_NYLIUM;
BlockData States::CRIMSON_FUNGUS;
BlockData States::SHROOMLIGHT;
BlockData States::WEEPING_VINES;
BlockData States::WEEPING_VINES_PLANT;
BlockData States::TWISTING_VINES;
BlockData States::TWISTING_VINES_PLANT;
BlockData States::CRIMSON_ROOTS;
BlockData States::CRIMSON_PLANKS;
BlockData States::WARPED_PLANKS;
BlockData States::CRIMSON_SLAB;
BlockData States::WARPED_SLAB;
BlockData States::CRIMSON_PRESSURE_PLATE;
BlockData States::WARPED_PRESSURE_PLATE;
BlockData States::CRIMSON_FENCE;
BlockData States::WARPED_FENCE;
BlockData States::CRIMSON_TRAPDOOR;
BlockData States::WARPED_TRAPDOOR;
BlockData States::CRIMSON_FENCE_GATE;
BlockData States::WARPED_FENCE_GATE;
BlockData States::CRIMSON_STAIRS;
BlockData States::WARPED_STAIRS;
BlockData States::CRIMSON_BUTTON;
BlockData States::WARPED_BUTTON;
BlockData States::CRIMSON_DOOR;
BlockData States::WARPED_DOOR;
BlockData States::CRIMSON_SIGN;
BlockData States::WARPED_SIGN;
BlockData States::CRIMSON_WALL_SIGN;
BlockData States::WARPED_WALL_SIGN;
BlockData States::STRUCTURE_BLOCK;
BlockData States::JIGSAW;
BlockData States::COMPOSTER;
BlockData States::TARGET;
BlockData States::BEE_NEST;
BlockData States::BEEHIVE;
BlockData States::HONEY_BLOCK;
BlockData States::HONEYCOMB_BLOCK;
BlockData States::NETHERITE_BLOCK;
BlockData States::ANCIENT_DEBRIS;
BlockData States::CRYING_OBSIDIAN;
BlockData States::RESPAWN_ANCHOR;
BlockData States::POTTED_CRIMSON_FUNGUS;
BlockData States::POTTED_WARPED_FUNGUS;
BlockData States::POTTED_CRIMSON_ROOTS;
BlockData States::POTTED_WARPED_ROOTS;
BlockData States::LODESTONE;
BlockData States::BLACKSTONE;
BlockData States::BLACKSTONE_STAIRS;
BlockData States::BLACKSTONE_WALL;
BlockData States::BLACKSTONE_SLAB;
BlockData States::POLISHED_BLACKSTONE;
BlockData States::POLISHED_BLACKSTONE_BRICKS;
BlockData States::CRACKED_POLISHED_BLACKSTONE_BRICKS;
BlockData States::CHISELED_POLISHED_BLACKSTONE;
BlockData States::POLISHED_BLACKSTONE_BRICK_SLAB;
BlockData States::POLISHED_BLACKSTONE_BRICK_STAIRS;
BlockData States::POLISHED_BLACKSTONE_BRICK_WALL;
BlockData States::GILDED_BLACKSTONE;
BlockData States::POLISHED_BLACKSTONE_STAIRS;
BlockData States::POLISHED_BLACKSTONE_SLAB;
BlockData States::POLISHED_BLACKSTONE_PRESSURE_PLATE;
BlockData States::POLISHED_BLACKSTONE_BUTTON;
BlockData States::POLISHED_BLACKSTONE_WALL;
BlockData States::CHISELED_NETHER_BRICKS;
BlockData States::CRACKED_NETHER_BRICKS;
BlockData States::QUARTZ_BRICKS;

void States::init() {
    AIR = Blocks::AIR->getDefaultState();
    STONE = Blocks::STONE->getDefaultState();
    GRANITE = Blocks::GRANITE->getDefaultState();
    POLISHED_GRANITE = Blocks::POLISHED_GRANITE->getDefaultState();
    DIORITE = Blocks::DIORITE->getDefaultState();
    POLISHED_DIORITE = Blocks::POLISHED_DIORITE->getDefaultState();
    ANDESITE = Blocks::ANDESITE->getDefaultState();
    POLISHED_ANDESITE = Blocks::POLISHED_ANDESITE->getDefaultState();
    GRASS_BLOCK = Blocks::GRASS_BLOCK->getDefaultState();
    DIRT = Blocks::DIRT->getDefaultState();
    COARSE_DIRT = Blocks::COARSE_DIRT->getDefaultState();
    PODZOL = Blocks::PODZOL->getDefaultState();
    COBBLESTONE = Blocks::COBBLESTONE->getDefaultState();
    OAK_PLANKS = Blocks::OAK_PLANKS->getDefaultState();
    SPRUCE_PLANKS = Blocks::SPRUCE_PLANKS->getDefaultState();
    BIRCH_PLANKS = Blocks::BIRCH_PLANKS->getDefaultState();
    JUNGLE_PLANKS = Blocks::JUNGLE_PLANKS->getDefaultState();
    ACACIA_PLANKS = Blocks::ACACIA_PLANKS->getDefaultState();
    DARK_OAK_PLANKS = Blocks::DARK_OAK_PLANKS->getDefaultState();
    OAK_SAPLING = Blocks::OAK_SAPLING->getDefaultState();
    SPRUCE_SAPLING = Blocks::SPRUCE_SAPLING->getDefaultState();
    BIRCH_SAPLING = Blocks::BIRCH_SAPLING->getDefaultState();
    JUNGLE_SAPLING = Blocks::JUNGLE_SAPLING->getDefaultState();
    ACACIA_SAPLING = Blocks::ACACIA_SAPLING->getDefaultState();
    DARK_OAK_SAPLING = Blocks::DARK_OAK_SAPLING->getDefaultState();
    BEDROCK = Blocks::BEDROCK->getDefaultState();
    WATER = Blocks::WATER->getDefaultState();
    LAVA = Blocks::LAVA->getDefaultState();
    SAND = Blocks::SAND->getDefaultState();
    RED_SAND = Blocks::RED_SAND->getDefaultState();
    GRAVEL = Blocks::GRAVEL->getDefaultState();
    GOLD_ORE = Blocks::GOLD_ORE->getDefaultState();
    IRON_ORE = Blocks::IRON_ORE->getDefaultState();
    COAL_ORE = Blocks::COAL_ORE->getDefaultState();
    NETHER_GOLD_ORE = Blocks::NETHER_GOLD_ORE->getDefaultState();
    OAK_LOG = Blocks::OAK_LOG->getDefaultState();
    SPRUCE_LOG = Blocks::SPRUCE_LOG->getDefaultState();
    BIRCH_LOG = Blocks::BIRCH_LOG->getDefaultState();
    JUNGLE_LOG = Blocks::JUNGLE_LOG->getDefaultState();
    ACACIA_LOG = Blocks::ACACIA_LOG->getDefaultState();
    DARK_OAK_LOG = Blocks::DARK_OAK_LOG->getDefaultState();
    STRIPPED_SPRUCE_LOG = Blocks::STRIPPED_SPRUCE_LOG->getDefaultState();
    STRIPPED_BIRCH_LOG = Blocks::STRIPPED_BIRCH_LOG->getDefaultState();
    STRIPPED_JUNGLE_LOG = Blocks::STRIPPED_JUNGLE_LOG->getDefaultState();
    STRIPPED_ACACIA_LOG = Blocks::STRIPPED_ACACIA_LOG->getDefaultState();
    STRIPPED_DARK_OAK_LOG = Blocks::STRIPPED_DARK_OAK_LOG->getDefaultState();
    STRIPPED_OAK_LOG = Blocks::STRIPPED_OAK_LOG->getDefaultState();
    OAK_WOOD = Blocks::OAK_WOOD->getDefaultState();
    SPRUCE_WOOD = Blocks::SPRUCE_WOOD->getDefaultState();
    BIRCH_WOOD = Blocks::BIRCH_WOOD->getDefaultState();
    JUNGLE_WOOD = Blocks::JUNGLE_WOOD->getDefaultState();
    ACACIA_WOOD = Blocks::ACACIA_WOOD->getDefaultState();
    DARK_OAK_WOOD = Blocks::DARK_OAK_WOOD->getDefaultState();
    STRIPPED_OAK_WOOD = Blocks::STRIPPED_OAK_WOOD->getDefaultState();
    STRIPPED_SPRUCE_WOOD = Blocks::STRIPPED_SPRUCE_WOOD->getDefaultState();
    STRIPPED_BIRCH_WOOD = Blocks::STRIPPED_BIRCH_WOOD->getDefaultState();
    STRIPPED_JUNGLE_WOOD = Blocks::STRIPPED_JUNGLE_WOOD->getDefaultState();
    STRIPPED_ACACIA_WOOD = Blocks::STRIPPED_ACACIA_WOOD->getDefaultState();
    STRIPPED_DARK_OAK_WOOD = Blocks::STRIPPED_DARK_OAK_WOOD->getDefaultState();
    OAK_LEAVES = Blocks::OAK_LEAVES->getDefaultState();
    SPRUCE_LEAVES = Blocks::SPRUCE_LEAVES->getDefaultState();
    BIRCH_LEAVES = Blocks::BIRCH_LEAVES->getDefaultState();
    JUNGLE_LEAVES = Blocks::JUNGLE_LEAVES->getDefaultState();
    ACACIA_LEAVES = Blocks::ACACIA_LEAVES->getDefaultState();
    DARK_OAK_LEAVES = Blocks::DARK_OAK_LEAVES->getDefaultState();
    SPONGE = Blocks::SPONGE->getDefaultState();
    WET_SPONGE = Blocks::WET_SPONGE->getDefaultState();
    GLASS = Blocks::GLASS->getDefaultState();
    LAPIS_ORE = Blocks::LAPIS_ORE->getDefaultState();
    LAPIS_BLOCK = Blocks::LAPIS_BLOCK->getDefaultState();
    DISPENSER = Blocks::DISPENSER->getDefaultState();
    SANDSTONE = Blocks::SANDSTONE->getDefaultState();
    CHISELED_SANDSTONE = Blocks::CHISELED_SANDSTONE->getDefaultState();
    CUT_SANDSTONE = Blocks::CUT_SANDSTONE->getDefaultState();
    NOTE_BLOCK = Blocks::NOTE_BLOCK->getDefaultState();
    WHITE_BED = Blocks::WHITE_BED->getDefaultState();
    ORANGE_BED = Blocks::ORANGE_BED->getDefaultState();
    MAGENTA_BED = Blocks::MAGENTA_BED->getDefaultState();
    LIGHT_BLUE_BED = Blocks::LIGHT_BLUE_BED->getDefaultState();
    YELLOW_BED = Blocks::YELLOW_BED->getDefaultState();
    LIME_BED = Blocks::LIME_BED->getDefaultState();
    PINK_BED = Blocks::PINK_BED->getDefaultState();
    GRAY_BED = Blocks::GRAY_BED->getDefaultState();
    LIGHT_GRAY_BED = Blocks::LIGHT_GRAY_BED->getDefaultState();
    CYAN_BED = Blocks::CYAN_BED->getDefaultState();
    PURPLE_BED = Blocks::PURPLE_BED->getDefaultState();
    BLUE_BED = Blocks::BLUE_BED->getDefaultState();
    BROWN_BED = Blocks::BROWN_BED->getDefaultState();
    GREEN_BED = Blocks::GREEN_BED->getDefaultState();
    RED_BED = Blocks::RED_BED->getDefaultState();
    BLACK_BED = Blocks::BLACK_BED->getDefaultState();
    POWERED_RAIL = Blocks::POWERED_RAIL->getDefaultState();
    DETECTOR_RAIL = Blocks::DETECTOR_RAIL->getDefaultState();
    STICKY_PISTON = Blocks::STICKY_PISTON->getDefaultState();
    COBWEB = Blocks::COBWEB->getDefaultState();
    GRASS = Blocks::GRASS->getDefaultState();
    FERN = Blocks::FERN->getDefaultState();
    DEAD_BUSH = Blocks::DEAD_BUSH->getDefaultState();
    SEAGRASS = Blocks::SEAGRASS->getDefaultState();
    TALL_SEAGRASS = Blocks::TALL_SEAGRASS->getDefaultState();
    PISTON = Blocks::PISTON->getDefaultState();
    PISTON_HEAD = Blocks::PISTON_HEAD->getDefaultState();
    WHITE_WOOL = Blocks::WHITE_WOOL->getDefaultState();
    ORANGE_WOOL = Blocks::ORANGE_WOOL->getDefaultState();
    MAGENTA_WOOL = Blocks::MAGENTA_WOOL->getDefaultState();
    LIGHT_BLUE_WOOL = Blocks::LIGHT_BLUE_WOOL->getDefaultState();
    YELLOW_WOOL = Blocks::YELLOW_WOOL->getDefaultState();
    LIME_WOOL = Blocks::LIME_WOOL->getDefaultState();
    PINK_WOOL = Blocks::PINK_WOOL->getDefaultState();
    GRAY_WOOL = Blocks::GRAY_WOOL->getDefaultState();
    LIGHT_GRAY_WOOL = Blocks::LIGHT_GRAY_WOOL->getDefaultState();
    CYAN_WOOL = Blocks::CYAN_WOOL->getDefaultState();
    PURPLE_WOOL = Blocks::PURPLE_WOOL->getDefaultState();
    BLUE_WOOL = Blocks::BLUE_WOOL->getDefaultState();
    BROWN_WOOL = Blocks::BROWN_WOOL->getDefaultState();
    GREEN_WOOL = Blocks::GREEN_WOOL->getDefaultState();
    RED_WOOL = Blocks::RED_WOOL->getDefaultState();
    BLACK_WOOL = Blocks::BLACK_WOOL->getDefaultState();
    MOVING_PISTON = Blocks::MOVING_PISTON->getDefaultState();
    DANDELION = Blocks::DANDELION->getDefaultState();
    POPPY = Blocks::POPPY->getDefaultState();
    BLUE_ORCHID = Blocks::BLUE_ORCHID->getDefaultState();
    ALLIUM = Blocks::ALLIUM->getDefaultState();
    AZURE_BLUET = Blocks::AZURE_BLUET->getDefaultState();
    RED_TULIP = Blocks::RED_TULIP->getDefaultState();
    ORANGE_TULIP = Blocks::ORANGE_TULIP->getDefaultState();
    WHITE_TULIP = Blocks::WHITE_TULIP->getDefaultState();
    PINK_TULIP = Blocks::PINK_TULIP->getDefaultState();
    OXEYE_DAISY = Blocks::OXEYE_DAISY->getDefaultState();
    CORNFLOWER = Blocks::CORNFLOWER->getDefaultState();
    WITHER_ROSE = Blocks::WITHER_ROSE->getDefaultState();
    LILY_OF_THE_VALLEY = Blocks::LILY_OF_THE_VALLEY->getDefaultState();
    BROWN_MUSHROOM = Blocks::BROWN_MUSHROOM->getDefaultState();
    RED_MUSHROOM = Blocks::RED_MUSHROOM->getDefaultState();
    GOLD_BLOCK = Blocks::GOLD_BLOCK->getDefaultState();
    IRON_BLOCK = Blocks::IRON_BLOCK->getDefaultState();
    BRICKS = Blocks::BRICKS->getDefaultState();
    TNT = Blocks::TNT->getDefaultState();
    BOOKSHELF = Blocks::BOOKSHELF->getDefaultState();
    MOSSY_COBBLESTONE = Blocks::MOSSY_COBBLESTONE->getDefaultState();
    OBSIDIAN = Blocks::OBSIDIAN->getDefaultState();
    TORCH = Blocks::TORCH->getDefaultState();
    WALL_TORCH = Blocks::WALL_TORCH->getDefaultState();
    FIRE = Blocks::FIRE->getDefaultState();
    SOUL_FIRE = Blocks::SOUL_FIRE->getDefaultState();
    SPAWNER = Blocks::SPAWNER->getDefaultState();
    OAK_STAIRS = Blocks::OAK_STAIRS->getDefaultState();
    CHEST = Blocks::CHEST->getDefaultState();
    REDSTONE_WIRE = Blocks::REDSTONE_WIRE->getDefaultState();
    DIAMOND_ORE = Blocks::DIAMOND_ORE->getDefaultState();
    DIAMOND_BLOCK = Blocks::DIAMOND_BLOCK->getDefaultState();
    CRAFTING_TABLE = Blocks::CRAFTING_TABLE->getDefaultState();
    WHEAT = Blocks::WHEAT->getDefaultState();
    FARMLAND = Blocks::FARMLAND->getDefaultState();
    FURNACE = Blocks::FURNACE->getDefaultState();
    OAK_SIGN = Blocks::OAK_SIGN->getDefaultState();
    SPRUCE_SIGN = Blocks::SPRUCE_SIGN->getDefaultState();
    BIRCH_SIGN = Blocks::BIRCH_SIGN->getDefaultState();
    ACACIA_SIGN = Blocks::ACACIA_SIGN->getDefaultState();
    JUNGLE_SIGN = Blocks::JUNGLE_SIGN->getDefaultState();
    DARK_OAK_SIGN = Blocks::DARK_OAK_SIGN->getDefaultState();
    OAK_DOOR = Blocks::OAK_DOOR->getDefaultState();
    LADDER = Blocks::LADDER->getDefaultState();
    RAIL = Blocks::RAIL->getDefaultState();
    COBBLESTONE_STAIRS = Blocks::COBBLESTONE_STAIRS->getDefaultState();
    OAK_WALL_SIGN = Blocks::OAK_WALL_SIGN->getDefaultState();
    SPRUCE_WALL_SIGN = Blocks::SPRUCE_WALL_SIGN->getDefaultState();
    BIRCH_WALL_SIGN = Blocks::BIRCH_WALL_SIGN->getDefaultState();
    ACACIA_WALL_SIGN = Blocks::ACACIA_WALL_SIGN->getDefaultState();
    JUNGLE_WALL_SIGN = Blocks::JUNGLE_WALL_SIGN->getDefaultState();
    DARK_OAK_WALL_SIGN = Blocks::DARK_OAK_WALL_SIGN->getDefaultState();
    LEVER = Blocks::LEVER->getDefaultState();
    STONE_PRESSURE_PLATE = Blocks::STONE_PRESSURE_PLATE->getDefaultState();
    IRON_DOOR = Blocks::IRON_DOOR->getDefaultState();
    OAK_PRESSURE_PLATE = Blocks::OAK_PRESSURE_PLATE->getDefaultState();
    SPRUCE_PRESSURE_PLATE = Blocks::SPRUCE_PRESSURE_PLATE->getDefaultState();
    BIRCH_PRESSURE_PLATE = Blocks::BIRCH_PRESSURE_PLATE->getDefaultState();
    JUNGLE_PRESSURE_PLATE = Blocks::JUNGLE_PRESSURE_PLATE->getDefaultState();
    ACACIA_PRESSURE_PLATE = Blocks::ACACIA_PRESSURE_PLATE->getDefaultState();
    DARK_OAK_PRESSURE_PLATE = Blocks::DARK_OAK_PRESSURE_PLATE->getDefaultState();
    REDSTONE_ORE = Blocks::REDSTONE_ORE->getDefaultState();
    REDSTONE_TORCH = Blocks::REDSTONE_TORCH->getDefaultState();
    REDSTONE_WALL_TORCH = Blocks::REDSTONE_WALL_TORCH->getDefaultState();
    STONE_BUTTON = Blocks::STONE_BUTTON->getDefaultState();
    SNOW = Blocks::SNOW->getDefaultState();
    ICE = Blocks::ICE->getDefaultState();
    SNOW_BLOCK = Blocks::SNOW_BLOCK->getDefaultState();
    CACTUS = Blocks::CACTUS->getDefaultState();
    CLAY = Blocks::CLAY->getDefaultState();
    SUGAR_CANE = Blocks::SUGAR_CANE->getDefaultState();
    JUKEBOX = Blocks::JUKEBOX->getDefaultState();
    OAK_FENCE = Blocks::OAK_FENCE->getDefaultState();
    PUMPKIN = Blocks::PUMPKIN->getDefaultState();
    NETHERRACK = Blocks::NETHERRACK->getDefaultState();
    SOUL_SAND = Blocks::SOUL_SAND->getDefaultState();
    SOUL_SOIL = Blocks::SOUL_SOIL->getDefaultState();
    BASALT = Blocks::BASALT->getDefaultState();
    POLISHED_BASALT = Blocks::POLISHED_BASALT->getDefaultState();
    SOUL_TORCH = Blocks::SOUL_TORCH->getDefaultState();
    SOUL_WALL_TORCH = Blocks::SOUL_WALL_TORCH->getDefaultState();
    GLOWSTONE = Blocks::GLOWSTONE->getDefaultState();
    NETHER_PORTAL = Blocks::NETHER_PORTAL->getDefaultState();
    CARVED_PUMPKIN = Blocks::CARVED_PUMPKIN->getDefaultState();
    JACK_O_LANTERN = Blocks::JACK_O_LANTERN->getDefaultState();
    CAKE = Blocks::CAKE->getDefaultState();
    REPEATER = Blocks::REPEATER->getDefaultState();
    WHITE_STAINED_GLASS = Blocks::WHITE_STAINED_GLASS->getDefaultState();
    ORANGE_STAINED_GLASS = Blocks::ORANGE_STAINED_GLASS->getDefaultState();
    MAGENTA_STAINED_GLASS = Blocks::MAGENTA_STAINED_GLASS->getDefaultState();
    LIGHT_BLUE_STAINED_GLASS = Blocks::LIGHT_BLUE_STAINED_GLASS->getDefaultState();
    YELLOW_STAINED_GLASS = Blocks::YELLOW_STAINED_GLASS->getDefaultState();
    LIME_STAINED_GLASS = Blocks::LIME_STAINED_GLASS->getDefaultState();
    PINK_STAINED_GLASS = Blocks::PINK_STAINED_GLASS->getDefaultState();
    GRAY_STAINED_GLASS = Blocks::GRAY_STAINED_GLASS->getDefaultState();
    LIGHT_GRAY_STAINED_GLASS = Blocks::LIGHT_GRAY_STAINED_GLASS->getDefaultState();
    CYAN_STAINED_GLASS = Blocks::CYAN_STAINED_GLASS->getDefaultState();
    PURPLE_STAINED_GLASS = Blocks::PURPLE_STAINED_GLASS->getDefaultState();
    BLUE_STAINED_GLASS = Blocks::BLUE_STAINED_GLASS->getDefaultState();
    BROWN_STAINED_GLASS = Blocks::BROWN_STAINED_GLASS->getDefaultState();
    GREEN_STAINED_GLASS = Blocks::GREEN_STAINED_GLASS->getDefaultState();
    RED_STAINED_GLASS = Blocks::RED_STAINED_GLASS->getDefaultState();
    BLACK_STAINED_GLASS = Blocks::BLACK_STAINED_GLASS->getDefaultState();
    OAK_TRAPDOOR = Blocks::OAK_TRAPDOOR->getDefaultState();
    SPRUCE_TRAPDOOR = Blocks::SPRUCE_TRAPDOOR->getDefaultState();
    BIRCH_TRAPDOOR = Blocks::BIRCH_TRAPDOOR->getDefaultState();
    JUNGLE_TRAPDOOR = Blocks::JUNGLE_TRAPDOOR->getDefaultState();
    ACACIA_TRAPDOOR = Blocks::ACACIA_TRAPDOOR->getDefaultState();
    DARK_OAK_TRAPDOOR = Blocks::DARK_OAK_TRAPDOOR->getDefaultState();
    STONE_BRICKS = Blocks::STONE_BRICKS->getDefaultState();
    MOSSY_STONE_BRICKS = Blocks::MOSSY_STONE_BRICKS->getDefaultState();
    CRACKED_STONE_BRICKS = Blocks::CRACKED_STONE_BRICKS->getDefaultState();
    CHISELED_STONE_BRICKS = Blocks::CHISELED_STONE_BRICKS->getDefaultState();
    INFESTED_STONE = Blocks::INFESTED_STONE->getDefaultState();
    INFESTED_COBBLESTONE = Blocks::INFESTED_COBBLESTONE->getDefaultState();
    INFESTED_STONE_BRICKS = Blocks::INFESTED_STONE_BRICKS->getDefaultState();
    INFESTED_MOSSY_STONE_BRICKS = Blocks::INFESTED_MOSSY_STONE_BRICKS->getDefaultState();
    INFESTED_CRACKED_STONE_BRICKS = Blocks::INFESTED_CRACKED_STONE_BRICKS->getDefaultState();
    INFESTED_CHISELED_STONE_BRICKS = Blocks::INFESTED_CHISELED_STONE_BRICKS->getDefaultState();
    BROWN_MUSHROOM_BLOCK = Blocks::BROWN_MUSHROOM_BLOCK->getDefaultState();
    RED_MUSHROOM_BLOCK = Blocks::RED_MUSHROOM_BLOCK->getDefaultState();
    MUSHROOM_STEM = Blocks::MUSHROOM_STEM->getDefaultState();
    IRON_BARS = Blocks::IRON_BARS->getDefaultState();
    CHAIN = Blocks::CHAIN->getDefaultState();
    GLASS_PANE = Blocks::GLASS_PANE->getDefaultState();
    MELON = Blocks::MELON->getDefaultState();
    ATTACHED_PUMPKIN_STEM = Blocks::ATTACHED_PUMPKIN_STEM->getDefaultState();
    ATTACHED_MELON_STEM = Blocks::ATTACHED_MELON_STEM->getDefaultState();
    PUMPKIN_STEM = Blocks::PUMPKIN_STEM->getDefaultState();
    MELON_STEM = Blocks::MELON_STEM->getDefaultState();
    VINE = Blocks::VINE->getDefaultState();
    OAK_FENCE_GATE = Blocks::OAK_FENCE_GATE->getDefaultState();
    BRICK_STAIRS = Blocks::BRICK_STAIRS->getDefaultState();
    STONE_BRICK_STAIRS = Blocks::STONE_BRICK_STAIRS->getDefaultState();
    MYCELIUM = Blocks::MYCELIUM->getDefaultState();
    LILY_PAD = Blocks::LILY_PAD->getDefaultState();
    NETHER_BRICKS = Blocks::NETHER_BRICKS->getDefaultState();
    NETHER_BRICK_FENCE = Blocks::NETHER_BRICK_FENCE->getDefaultState();
    NETHER_BRICK_STAIRS = Blocks::NETHER_BRICK_STAIRS->getDefaultState();
    NETHER_WART = Blocks::NETHER_WART->getDefaultState();
    ENCHANTING_TABLE = Blocks::ENCHANTING_TABLE->getDefaultState();
    BREWING_STAND = Blocks::BREWING_STAND->getDefaultState();
    CAULDRON = Blocks::CAULDRON->getDefaultState();
    END_PORTAL = Blocks::END_PORTAL->getDefaultState();
    END_PORTAL_FRAME = Blocks::END_PORTAL_FRAME->getDefaultState();
    END_STONE = Blocks::END_STONE->getDefaultState();
    DRAGON_EGG = Blocks::DRAGON_EGG->getDefaultState();
    REDSTONE_LAMP = Blocks::REDSTONE_LAMP->getDefaultState();
    COCOA = Blocks::COCOA->getDefaultState();
    SANDSTONE_STAIRS = Blocks::SANDSTONE_STAIRS->getDefaultState();
    EMERALD_ORE = Blocks::EMERALD_ORE->getDefaultState();
    ENDER_CHEST = Blocks::ENDER_CHEST->getDefaultState();
    TRIPWIRE_HOOK = Blocks::TRIPWIRE_HOOK->getDefaultState();
    TRIPWIRE = Blocks::TRIPWIRE->getDefaultState();
    EMERALD_BLOCK = Blocks::EMERALD_BLOCK->getDefaultState();
    SPRUCE_STAIRS = Blocks::SPRUCE_STAIRS->getDefaultState();
    BIRCH_STAIRS = Blocks::BIRCH_STAIRS->getDefaultState();
    JUNGLE_STAIRS = Blocks::JUNGLE_STAIRS->getDefaultState();
    COMMAND_BLOCK = Blocks::COMMAND_BLOCK->getDefaultState();
    BEACON = Blocks::BEACON->getDefaultState();
    COBBLESTONE_WALL = Blocks::COBBLESTONE_WALL->getDefaultState();
    MOSSY_COBBLESTONE_WALL = Blocks::MOSSY_COBBLESTONE_WALL->getDefaultState();
    FLOWER_POT = Blocks::FLOWER_POT->getDefaultState();
    POTTED_OAK_SAPLING = Blocks::POTTED_OAK_SAPLING->getDefaultState();
    POTTED_SPRUCE_SAPLING = Blocks::POTTED_SPRUCE_SAPLING->getDefaultState();
    POTTED_BIRCH_SAPLING = Blocks::POTTED_BIRCH_SAPLING->getDefaultState();
    POTTED_JUNGLE_SAPLING = Blocks::POTTED_JUNGLE_SAPLING->getDefaultState();
    POTTED_ACACIA_SAPLING = Blocks::POTTED_ACACIA_SAPLING->getDefaultState();
    POTTED_DARK_OAK_SAPLING = Blocks::POTTED_DARK_OAK_SAPLING->getDefaultState();
    POTTED_FERN = Blocks::POTTED_FERN->getDefaultState();
    POTTED_DANDELION = Blocks::POTTED_DANDELION->getDefaultState();
    POTTED_POPPY = Blocks::POTTED_POPPY->getDefaultState();
    POTTED_BLUE_ORCHID = Blocks::POTTED_BLUE_ORCHID->getDefaultState();
    POTTED_ALLIUM = Blocks::POTTED_ALLIUM->getDefaultState();
    POTTED_AZURE_BLUET = Blocks::POTTED_AZURE_BLUET->getDefaultState();
    POTTED_RED_TULIP = Blocks::POTTED_RED_TULIP->getDefaultState();
    POTTED_ORANGE_TULIP = Blocks::POTTED_ORANGE_TULIP->getDefaultState();
    POTTED_WHITE_TULIP = Blocks::POTTED_WHITE_TULIP->getDefaultState();
    POTTED_PINK_TULIP = Blocks::POTTED_PINK_TULIP->getDefaultState();
    POTTED_OXEYE_DAISY = Blocks::POTTED_OXEYE_DAISY->getDefaultState();
    POTTED_CORNFLOWER = Blocks::POTTED_CORNFLOWER->getDefaultState();
    POTTED_LILY_OF_THE_VALLEY = Blocks::POTTED_LILY_OF_THE_VALLEY->getDefaultState();
    POTTED_WITHER_ROSE = Blocks::POTTED_WITHER_ROSE->getDefaultState();
    POTTED_RED_MUSHROOM = Blocks::POTTED_RED_MUSHROOM->getDefaultState();
    POTTED_BROWN_MUSHROOM = Blocks::POTTED_BROWN_MUSHROOM->getDefaultState();
    POTTED_DEAD_BUSH = Blocks::POTTED_DEAD_BUSH->getDefaultState();
    POTTED_CACTUS = Blocks::POTTED_CACTUS->getDefaultState();
    CARROTS = Blocks::CARROTS->getDefaultState();
    POTATOES = Blocks::POTATOES->getDefaultState();
    OAK_BUTTON = Blocks::OAK_BUTTON->getDefaultState();
    SPRUCE_BUTTON = Blocks::SPRUCE_BUTTON->getDefaultState();
    BIRCH_BUTTON = Blocks::BIRCH_BUTTON->getDefaultState();
    JUNGLE_BUTTON = Blocks::JUNGLE_BUTTON->getDefaultState();
    ACACIA_BUTTON = Blocks::ACACIA_BUTTON->getDefaultState();
    DARK_OAK_BUTTON = Blocks::DARK_OAK_BUTTON->getDefaultState();
    SKELETON_SKULL = Blocks::SKELETON_SKULL->getDefaultState();
    SKELETON_WALL_SKULL = Blocks::SKELETON_WALL_SKULL->getDefaultState();
    WITHER_SKELETON_SKULL = Blocks::WITHER_SKELETON_SKULL->getDefaultState();
    WITHER_SKELETON_WALL_SKULL = Blocks::WITHER_SKELETON_WALL_SKULL->getDefaultState();
    ZOMBIE_HEAD = Blocks::ZOMBIE_HEAD->getDefaultState();
    ZOMBIE_WALL_HEAD = Blocks::ZOMBIE_WALL_HEAD->getDefaultState();
    PLAYER_HEAD = Blocks::PLAYER_HEAD->getDefaultState();
    PLAYER_WALL_HEAD = Blocks::PLAYER_WALL_HEAD->getDefaultState();
    CREEPER_HEAD = Blocks::CREEPER_HEAD->getDefaultState();
    CREEPER_WALL_HEAD = Blocks::CREEPER_WALL_HEAD->getDefaultState();
    DRAGON_HEAD = Blocks::DRAGON_HEAD->getDefaultState();
    DRAGON_WALL_HEAD = Blocks::DRAGON_WALL_HEAD->getDefaultState();
    ANVIL = Blocks::ANVIL->getDefaultState();
    CHIPPED_ANVIL = Blocks::CHIPPED_ANVIL->getDefaultState();
    DAMAGED_ANVIL = Blocks::DAMAGED_ANVIL->getDefaultState();
    TRAPPED_CHEST = Blocks::TRAPPED_CHEST->getDefaultState();
    LIGHT_WEIGHTED_PRESSURE_PLATE = Blocks::LIGHT_WEIGHTED_PRESSURE_PLATE->getDefaultState();
    HEAVY_WEIGHTED_PRESSURE_PLATE = Blocks::HEAVY_WEIGHTED_PRESSURE_PLATE->getDefaultState();
    COMPARATOR = Blocks::COMPARATOR->getDefaultState();
    DAYLIGHT_DETECTOR = Blocks::DAYLIGHT_DETECTOR->getDefaultState();
    REDSTONE_BLOCK = Blocks::REDSTONE_BLOCK->getDefaultState();
    NETHER_QUARTZ_ORE = Blocks::NETHER_QUARTZ_ORE->getDefaultState();
    HOPPER = Blocks::HOPPER->getDefaultState();
    QUARTZ_BLOCK = Blocks::QUARTZ_BLOCK->getDefaultState();
    CHISELED_QUARTZ_BLOCK = Blocks::CHISELED_QUARTZ_BLOCK->getDefaultState();
    QUARTZ_PILLAR = Blocks::QUARTZ_PILLAR->getDefaultState();
    QUARTZ_STAIRS = Blocks::QUARTZ_STAIRS->getDefaultState();
    ACTIVATOR_RAIL = Blocks::ACTIVATOR_RAIL->getDefaultState();
    DROPPER = Blocks::DROPPER->getDefaultState();
    WHITE_TERRACOTTA = Blocks::WHITE_TERRACOTTA->getDefaultState();
    ORANGE_TERRACOTTA = Blocks::ORANGE_TERRACOTTA->getDefaultState();
    MAGENTA_TERRACOTTA = Blocks::MAGENTA_TERRACOTTA->getDefaultState();
    LIGHT_BLUE_TERRACOTTA = Blocks::LIGHT_BLUE_TERRACOTTA->getDefaultState();
    YELLOW_TERRACOTTA = Blocks::YELLOW_TERRACOTTA->getDefaultState();
    LIME_TERRACOTTA = Blocks::LIME_TERRACOTTA->getDefaultState();
    PINK_TERRACOTTA = Blocks::PINK_TERRACOTTA->getDefaultState();
    GRAY_TERRACOTTA = Blocks::GRAY_TERRACOTTA->getDefaultState();
    LIGHT_GRAY_TERRACOTTA = Blocks::LIGHT_GRAY_TERRACOTTA->getDefaultState();
    CYAN_TERRACOTTA = Blocks::CYAN_TERRACOTTA->getDefaultState();
    PURPLE_TERRACOTTA = Blocks::PURPLE_TERRACOTTA->getDefaultState();
    BLUE_TERRACOTTA = Blocks::BLUE_TERRACOTTA->getDefaultState();
    BROWN_TERRACOTTA = Blocks::BROWN_TERRACOTTA->getDefaultState();
    GREEN_TERRACOTTA = Blocks::GREEN_TERRACOTTA->getDefaultState();
    RED_TERRACOTTA = Blocks::RED_TERRACOTTA->getDefaultState();
    BLACK_TERRACOTTA = Blocks::BLACK_TERRACOTTA->getDefaultState();
    WHITE_STAINED_GLASS_PANE = Blocks::WHITE_STAINED_GLASS_PANE->getDefaultState();
    ORANGE_STAINED_GLASS_PANE = Blocks::ORANGE_STAINED_GLASS_PANE->getDefaultState();
    MAGENTA_STAINED_GLASS_PANE = Blocks::MAGENTA_STAINED_GLASS_PANE->getDefaultState();
    LIGHT_BLUE_STAINED_GLASS_PANE = Blocks::LIGHT_BLUE_STAINED_GLASS_PANE->getDefaultState();
    YELLOW_STAINED_GLASS_PANE = Blocks::YELLOW_STAINED_GLASS_PANE->getDefaultState();
    LIME_STAINED_GLASS_PANE = Blocks::LIME_STAINED_GLASS_PANE->getDefaultState();
    PINK_STAINED_GLASS_PANE = Blocks::PINK_STAINED_GLASS_PANE->getDefaultState();
    GRAY_STAINED_GLASS_PANE = Blocks::GRAY_STAINED_GLASS_PANE->getDefaultState();
    LIGHT_GRAY_STAINED_GLASS_PANE = Blocks::LIGHT_GRAY_STAINED_GLASS_PANE->getDefaultState();
    CYAN_STAINED_GLASS_PANE = Blocks::CYAN_STAINED_GLASS_PANE->getDefaultState();
    PURPLE_STAINED_GLASS_PANE = Blocks::PURPLE_STAINED_GLASS_PANE->getDefaultState();
    BLUE_STAINED_GLASS_PANE = Blocks::BLUE_STAINED_GLASS_PANE->getDefaultState();
    BROWN_STAINED_GLASS_PANE = Blocks::BROWN_STAINED_GLASS_PANE->getDefaultState();
    GREEN_STAINED_GLASS_PANE = Blocks::GREEN_STAINED_GLASS_PANE->getDefaultState();
    RED_STAINED_GLASS_PANE = Blocks::RED_STAINED_GLASS_PANE->getDefaultState();
    BLACK_STAINED_GLASS_PANE = Blocks::BLACK_STAINED_GLASS_PANE->getDefaultState();
    ACACIA_STAIRS = Blocks::ACACIA_STAIRS->getDefaultState();
    DARK_OAK_STAIRS = Blocks::DARK_OAK_STAIRS->getDefaultState();
    SLIME_BLOCK = Blocks::SLIME_BLOCK->getDefaultState();
    BARRIER = Blocks::BARRIER->getDefaultState();
    IRON_TRAPDOOR = Blocks::IRON_TRAPDOOR->getDefaultState();
    PRISMARINE = Blocks::PRISMARINE->getDefaultState();
    PRISMARINE_BRICKS = Blocks::PRISMARINE_BRICKS->getDefaultState();
    DARK_PRISMARINE = Blocks::DARK_PRISMARINE->getDefaultState();
    PRISMARINE_STAIRS = Blocks::PRISMARINE_STAIRS->getDefaultState();
    PRISMARINE_BRICK_STAIRS = Blocks::PRISMARINE_BRICK_STAIRS->getDefaultState();
    DARK_PRISMARINE_STAIRS = Blocks::DARK_PRISMARINE_STAIRS->getDefaultState();
    PRISMARINE_SLAB = Blocks::PRISMARINE_SLAB->getDefaultState();
    PRISMARINE_BRICK_SLAB = Blocks::PRISMARINE_BRICK_SLAB->getDefaultState();
    DARK_PRISMARINE_SLAB = Blocks::DARK_PRISMARINE_SLAB->getDefaultState();
    SEA_LANTERN = Blocks::SEA_LANTERN->getDefaultState();
    HAY_BLOCK = Blocks::HAY_BLOCK->getDefaultState();
    WHITE_CARPET = Blocks::WHITE_CARPET->getDefaultState();
    ORANGE_CARPET = Blocks::ORANGE_CARPET->getDefaultState();
    MAGENTA_CARPET = Blocks::MAGENTA_CARPET->getDefaultState();
    LIGHT_BLUE_CARPET = Blocks::LIGHT_BLUE_CARPET->getDefaultState();
    YELLOW_CARPET = Blocks::YELLOW_CARPET->getDefaultState();
    LIME_CARPET = Blocks::LIME_CARPET->getDefaultState();
    PINK_CARPET = Blocks::PINK_CARPET->getDefaultState();
    GRAY_CARPET = Blocks::GRAY_CARPET->getDefaultState();
    LIGHT_GRAY_CARPET = Blocks::LIGHT_GRAY_CARPET->getDefaultState();
    CYAN_CARPET = Blocks::CYAN_CARPET->getDefaultState();
    PURPLE_CARPET = Blocks::PURPLE_CARPET->getDefaultState();
    BLUE_CARPET = Blocks::BLUE_CARPET->getDefaultState();
    BROWN_CARPET = Blocks::BROWN_CARPET->getDefaultState();
    GREEN_CARPET = Blocks::GREEN_CARPET->getDefaultState();
    RED_CARPET = Blocks::RED_CARPET->getDefaultState();
    BLACK_CARPET = Blocks::BLACK_CARPET->getDefaultState();
    TERRACOTTA = Blocks::TERRACOTTA->getDefaultState();
    COAL_BLOCK = Blocks::COAL_BLOCK->getDefaultState();
    PACKED_ICE = Blocks::PACKED_ICE->getDefaultState();
    SUNFLOWER = Blocks::SUNFLOWER->getDefaultState();
    LILAC = Blocks::LILAC->getDefaultState();
    ROSE_BUSH = Blocks::ROSE_BUSH->getDefaultState();
    PEONY = Blocks::PEONY->getDefaultState();
    TALL_GRASS = Blocks::TALL_GRASS->getDefaultState();
    LARGE_FERN = Blocks::LARGE_FERN->getDefaultState();
    WHITE_BANNER = Blocks::WHITE_BANNER->getDefaultState();
    ORANGE_BANNER = Blocks::ORANGE_BANNER->getDefaultState();
    MAGENTA_BANNER = Blocks::MAGENTA_BANNER->getDefaultState();
    LIGHT_BLUE_BANNER = Blocks::LIGHT_BLUE_BANNER->getDefaultState();
    YELLOW_BANNER = Blocks::YELLOW_BANNER->getDefaultState();
    LIME_BANNER = Blocks::LIME_BANNER->getDefaultState();
    PINK_BANNER = Blocks::PINK_BANNER->getDefaultState();
    GRAY_BANNER = Blocks::GRAY_BANNER->getDefaultState();
    LIGHT_GRAY_BANNER = Blocks::LIGHT_GRAY_BANNER->getDefaultState();
    CYAN_BANNER = Blocks::CYAN_BANNER->getDefaultState();
    PURPLE_BANNER = Blocks::PURPLE_BANNER->getDefaultState();
    BLUE_BANNER = Blocks::BLUE_BANNER->getDefaultState();
    BROWN_BANNER = Blocks::BROWN_BANNER->getDefaultState();
    GREEN_BANNER = Blocks::GREEN_BANNER->getDefaultState();
    RED_BANNER = Blocks::RED_BANNER->getDefaultState();
    BLACK_BANNER = Blocks::BLACK_BANNER->getDefaultState();
    WHITE_WALL_BANNER = Blocks::WHITE_WALL_BANNER->getDefaultState();
    ORANGE_WALL_BANNER = Blocks::ORANGE_WALL_BANNER->getDefaultState();
    MAGENTA_WALL_BANNER = Blocks::MAGENTA_WALL_BANNER->getDefaultState();
    LIGHT_BLUE_WALL_BANNER = Blocks::LIGHT_BLUE_WALL_BANNER->getDefaultState();
    YELLOW_WALL_BANNER = Blocks::YELLOW_WALL_BANNER->getDefaultState();
    LIME_WALL_BANNER = Blocks::LIME_WALL_BANNER->getDefaultState();
    PINK_WALL_BANNER = Blocks::PINK_WALL_BANNER->getDefaultState();
    GRAY_WALL_BANNER = Blocks::GRAY_WALL_BANNER->getDefaultState();
    LIGHT_GRAY_WALL_BANNER = Blocks::LIGHT_GRAY_WALL_BANNER->getDefaultState();
    CYAN_WALL_BANNER = Blocks::CYAN_WALL_BANNER->getDefaultState();
    PURPLE_WALL_BANNER = Blocks::PURPLE_WALL_BANNER->getDefaultState();
    BLUE_WALL_BANNER = Blocks::BLUE_WALL_BANNER->getDefaultState();
    BROWN_WALL_BANNER = Blocks::BROWN_WALL_BANNER->getDefaultState();
    GREEN_WALL_BANNER = Blocks::GREEN_WALL_BANNER->getDefaultState();
    RED_WALL_BANNER = Blocks::RED_WALL_BANNER->getDefaultState();
    BLACK_WALL_BANNER = Blocks::BLACK_WALL_BANNER->getDefaultState();
    RED_SANDSTONE = Blocks::RED_SANDSTONE->getDefaultState();
    CHISELED_RED_SANDSTONE = Blocks::CHISELED_RED_SANDSTONE->getDefaultState();
    CUT_RED_SANDSTONE = Blocks::CUT_RED_SANDSTONE->getDefaultState();
    RED_SANDSTONE_STAIRS = Blocks::RED_SANDSTONE_STAIRS->getDefaultState();
    OAK_SLAB = Blocks::OAK_SLAB->getDefaultState();
    SPRUCE_SLAB = Blocks::SPRUCE_SLAB->getDefaultState();
    BIRCH_SLAB = Blocks::BIRCH_SLAB->getDefaultState();
    JUNGLE_SLAB = Blocks::JUNGLE_SLAB->getDefaultState();
    ACACIA_SLAB = Blocks::ACACIA_SLAB->getDefaultState();
    DARK_OAK_SLAB = Blocks::DARK_OAK_SLAB->getDefaultState();
    STONE_SLAB = Blocks::STONE_SLAB->getDefaultState();
    SMOOTH_STONE_SLAB = Blocks::SMOOTH_STONE_SLAB->getDefaultState();
    SANDSTONE_SLAB = Blocks::SANDSTONE_SLAB->getDefaultState();
    CUT_SANDSTONE_SLAB = Blocks::CUT_SANDSTONE_SLAB->getDefaultState();
    PETRIFIED_OAK_SLAB = Blocks::PETRIFIED_OAK_SLAB->getDefaultState();
    COBBLESTONE_SLAB = Blocks::COBBLESTONE_SLAB->getDefaultState();
    BRICK_SLAB = Blocks::BRICK_SLAB->getDefaultState();
    STONE_BRICK_SLAB = Blocks::STONE_BRICK_SLAB->getDefaultState();
    NETHER_BRICK_SLAB = Blocks::NETHER_BRICK_SLAB->getDefaultState();
    QUARTZ_SLAB = Blocks::QUARTZ_SLAB->getDefaultState();
    RED_SANDSTONE_SLAB = Blocks::RED_SANDSTONE_SLAB->getDefaultState();
    CUT_RED_SANDSTONE_SLAB = Blocks::CUT_RED_SANDSTONE_SLAB->getDefaultState();
    PURPUR_SLAB = Blocks::PURPUR_SLAB->getDefaultState();
    SMOOTH_STONE = Blocks::SMOOTH_STONE->getDefaultState();
    SMOOTH_SANDSTONE = Blocks::SMOOTH_SANDSTONE->getDefaultState();
    SMOOTH_QUARTZ = Blocks::SMOOTH_QUARTZ->getDefaultState();
    SMOOTH_RED_SANDSTONE = Blocks::SMOOTH_RED_SANDSTONE->getDefaultState();
    SPRUCE_FENCE_GATE = Blocks::SPRUCE_FENCE_GATE->getDefaultState();
    BIRCH_FENCE_GATE = Blocks::BIRCH_FENCE_GATE->getDefaultState();
    JUNGLE_FENCE_GATE = Blocks::JUNGLE_FENCE_GATE->getDefaultState();
    ACACIA_FENCE_GATE = Blocks::ACACIA_FENCE_GATE->getDefaultState();
    DARK_OAK_FENCE_GATE = Blocks::DARK_OAK_FENCE_GATE->getDefaultState();
    SPRUCE_FENCE = Blocks::SPRUCE_FENCE->getDefaultState();
    BIRCH_FENCE = Blocks::BIRCH_FENCE->getDefaultState();
    JUNGLE_FENCE = Blocks::JUNGLE_FENCE->getDefaultState();
    ACACIA_FENCE = Blocks::ACACIA_FENCE->getDefaultState();
    DARK_OAK_FENCE = Blocks::DARK_OAK_FENCE->getDefaultState();
    SPRUCE_DOOR = Blocks::SPRUCE_DOOR->getDefaultState();
    BIRCH_DOOR = Blocks::BIRCH_DOOR->getDefaultState();
    JUNGLE_DOOR = Blocks::JUNGLE_DOOR->getDefaultState();
    ACACIA_DOOR = Blocks::ACACIA_DOOR->getDefaultState();
    DARK_OAK_DOOR = Blocks::DARK_OAK_DOOR->getDefaultState();
    END_ROD = Blocks::END_ROD->getDefaultState();
    CHORUS_PLANT = Blocks::CHORUS_PLANT->getDefaultState();
    CHORUS_FLOWER = Blocks::CHORUS_FLOWER->getDefaultState();
    PURPUR_BLOCK = Blocks::PURPUR_BLOCK->getDefaultState();
    PURPUR_PILLAR = Blocks::PURPUR_PILLAR->getDefaultState();
    PURPUR_STAIRS = Blocks::PURPUR_STAIRS->getDefaultState();
    END_STONE_BRICKS = Blocks::END_STONE_BRICKS->getDefaultState();
    BEETROOTS = Blocks::BEETROOTS->getDefaultState();
    GRASS_PATH = Blocks::GRASS_PATH->getDefaultState();
    END_GATEWAY = Blocks::END_GATEWAY->getDefaultState();
    REPEATING_COMMAND_BLOCK = Blocks::REPEATING_COMMAND_BLOCK->getDefaultState();
    CHAIN_COMMAND_BLOCK = Blocks::CHAIN_COMMAND_BLOCK->getDefaultState();
    FROSTED_ICE = Blocks::FROSTED_ICE->getDefaultState();
    MAGMA_BLOCK = Blocks::MAGMA_BLOCK->getDefaultState();
    NETHER_WART_BLOCK = Blocks::NETHER_WART_BLOCK->getDefaultState();
    RED_NETHER_BRICKS = Blocks::RED_NETHER_BRICKS->getDefaultState();
    BONE_BLOCK = Blocks::BONE_BLOCK->getDefaultState();
    STRUCTURE_VOID = Blocks::STRUCTURE_VOID->getDefaultState();
    OBSERVER = Blocks::OBSERVER->getDefaultState();
    SHULKER_BOX = Blocks::SHULKER_BOX->getDefaultState();
    WHITE_SHULKER_BOX = Blocks::WHITE_SHULKER_BOX->getDefaultState();
    ORANGE_SHULKER_BOX = Blocks::ORANGE_SHULKER_BOX->getDefaultState();
    MAGENTA_SHULKER_BOX = Blocks::MAGENTA_SHULKER_BOX->getDefaultState();
    LIGHT_BLUE_SHULKER_BOX = Blocks::LIGHT_BLUE_SHULKER_BOX->getDefaultState();
    YELLOW_SHULKER_BOX = Blocks::YELLOW_SHULKER_BOX->getDefaultState();
    LIME_SHULKER_BOX = Blocks::LIME_SHULKER_BOX->getDefaultState();
    PINK_SHULKER_BOX = Blocks::PINK_SHULKER_BOX->getDefaultState();
    GRAY_SHULKER_BOX = Blocks::GRAY_SHULKER_BOX->getDefaultState();
    LIGHT_GRAY_SHULKER_BOX = Blocks::LIGHT_GRAY_SHULKER_BOX->getDefaultState();
    CYAN_SHULKER_BOX = Blocks::CYAN_SHULKER_BOX->getDefaultState();
    PURPLE_SHULKER_BOX = Blocks::PURPLE_SHULKER_BOX->getDefaultState();
    BLUE_SHULKER_BOX = Blocks::BLUE_SHULKER_BOX->getDefaultState();
    BROWN_SHULKER_BOX = Blocks::BROWN_SHULKER_BOX->getDefaultState();
    GREEN_SHULKER_BOX = Blocks::GREEN_SHULKER_BOX->getDefaultState();
    RED_SHULKER_BOX = Blocks::RED_SHULKER_BOX->getDefaultState();
    BLACK_SHULKER_BOX = Blocks::BLACK_SHULKER_BOX->getDefaultState();
    WHITE_GLAZED_TERRACOTTA = Blocks::WHITE_GLAZED_TERRACOTTA->getDefaultState();
    ORANGE_GLAZED_TERRACOTTA = Blocks::ORANGE_GLAZED_TERRACOTTA->getDefaultState();
    MAGENTA_GLAZED_TERRACOTTA = Blocks::MAGENTA_GLAZED_TERRACOTTA->getDefaultState();
    LIGHT_BLUE_GLAZED_TERRACOTTA = Blocks::LIGHT_BLUE_GLAZED_TERRACOTTA->getDefaultState();
    YELLOW_GLAZED_TERRACOTTA = Blocks::YELLOW_GLAZED_TERRACOTTA->getDefaultState();
    LIME_GLAZED_TERRACOTTA = Blocks::LIME_GLAZED_TERRACOTTA->getDefaultState();
    PINK_GLAZED_TERRACOTTA = Blocks::PINK_GLAZED_TERRACOTTA->getDefaultState();
    GRAY_GLAZED_TERRACOTTA = Blocks::GRAY_GLAZED_TERRACOTTA->getDefaultState();
    LIGHT_GRAY_GLAZED_TERRACOTTA = Blocks::LIGHT_GRAY_GLAZED_TERRACOTTA->getDefaultState();
    CYAN_GLAZED_TERRACOTTA = Blocks::CYAN_GLAZED_TERRACOTTA->getDefaultState();
    PURPLE_GLAZED_TERRACOTTA = Blocks::PURPLE_GLAZED_TERRACOTTA->getDefaultState();
    BLUE_GLAZED_TERRACOTTA = Blocks::BLUE_GLAZED_TERRACOTTA->getDefaultState();
    BROWN_GLAZED_TERRACOTTA = Blocks::BROWN_GLAZED_TERRACOTTA->getDefaultState();
    GREEN_GLAZED_TERRACOTTA = Blocks::GREEN_GLAZED_TERRACOTTA->getDefaultState();
    RED_GLAZED_TERRACOTTA = Blocks::RED_GLAZED_TERRACOTTA->getDefaultState();
    BLACK_GLAZED_TERRACOTTA = Blocks::BLACK_GLAZED_TERRACOTTA->getDefaultState();
    WHITE_CONCRETE = Blocks::WHITE_CONCRETE->getDefaultState();
    ORANGE_CONCRETE = Blocks::ORANGE_CONCRETE->getDefaultState();
    MAGENTA_CONCRETE = Blocks::MAGENTA_CONCRETE->getDefaultState();
    LIGHT_BLUE_CONCRETE = Blocks::LIGHT_BLUE_CONCRETE->getDefaultState();
    YELLOW_CONCRETE = Blocks::YELLOW_CONCRETE->getDefaultState();
    LIME_CONCRETE = Blocks::LIME_CONCRETE->getDefaultState();
    PINK_CONCRETE = Blocks::PINK_CONCRETE->getDefaultState();
    GRAY_CONCRETE = Blocks::GRAY_CONCRETE->getDefaultState();
    LIGHT_GRAY_CONCRETE = Blocks::LIGHT_GRAY_CONCRETE->getDefaultState();
    CYAN_CONCRETE = Blocks::CYAN_CONCRETE->getDefaultState();
    PURPLE_CONCRETE = Blocks::PURPLE_CONCRETE->getDefaultState();
    BLUE_CONCRETE = Blocks::BLUE_CONCRETE->getDefaultState();
    BROWN_CONCRETE = Blocks::BROWN_CONCRETE->getDefaultState();
    GREEN_CONCRETE = Blocks::GREEN_CONCRETE->getDefaultState();
    RED_CONCRETE = Blocks::RED_CONCRETE->getDefaultState();
    BLACK_CONCRETE = Blocks::BLACK_CONCRETE->getDefaultState();
    WHITE_CONCRETE_POWDER = Blocks::WHITE_CONCRETE_POWDER->getDefaultState();
    ORANGE_CONCRETE_POWDER = Blocks::ORANGE_CONCRETE_POWDER->getDefaultState();
    MAGENTA_CONCRETE_POWDER = Blocks::MAGENTA_CONCRETE_POWDER->getDefaultState();
    LIGHT_BLUE_CONCRETE_POWDER = Blocks::LIGHT_BLUE_CONCRETE_POWDER->getDefaultState();
    YELLOW_CONCRETE_POWDER = Blocks::YELLOW_CONCRETE_POWDER->getDefaultState();
    LIME_CONCRETE_POWDER = Blocks::LIME_CONCRETE_POWDER->getDefaultState();
    PINK_CONCRETE_POWDER = Blocks::PINK_CONCRETE_POWDER->getDefaultState();
    GRAY_CONCRETE_POWDER = Blocks::GRAY_CONCRETE_POWDER->getDefaultState();
    LIGHT_GRAY_CONCRETE_POWDER = Blocks::LIGHT_GRAY_CONCRETE_POWDER->getDefaultState();
    CYAN_CONCRETE_POWDER = Blocks::CYAN_CONCRETE_POWDER->getDefaultState();
    PURPLE_CONCRETE_POWDER = Blocks::PURPLE_CONCRETE_POWDER->getDefaultState();
    BLUE_CONCRETE_POWDER = Blocks::BLUE_CONCRETE_POWDER->getDefaultState();
    BROWN_CONCRETE_POWDER = Blocks::BROWN_CONCRETE_POWDER->getDefaultState();
    GREEN_CONCRETE_POWDER = Blocks::GREEN_CONCRETE_POWDER->getDefaultState();
    RED_CONCRETE_POWDER = Blocks::RED_CONCRETE_POWDER->getDefaultState();
    BLACK_CONCRETE_POWDER = Blocks::BLACK_CONCRETE_POWDER->getDefaultState();
    KELP = Blocks::KELP->getDefaultState();
    KELP_PLANT = Blocks::KELP_PLANT->getDefaultState();
    DRIED_KELP_BLOCK = Blocks::DRIED_KELP_BLOCK->getDefaultState();
    TURTLE_EGG = Blocks::TURTLE_EGG->getDefaultState();
    DEAD_TUBE_CORAL_BLOCK = Blocks::DEAD_TUBE_CORAL_BLOCK->getDefaultState();
    DEAD_BRAIN_CORAL_BLOCK = Blocks::DEAD_BRAIN_CORAL_BLOCK->getDefaultState();
    DEAD_BUBBLE_CORAL_BLOCK = Blocks::DEAD_BUBBLE_CORAL_BLOCK->getDefaultState();
    DEAD_FIRE_CORAL_BLOCK = Blocks::DEAD_FIRE_CORAL_BLOCK->getDefaultState();
    DEAD_HORN_CORAL_BLOCK = Blocks::DEAD_HORN_CORAL_BLOCK->getDefaultState();
    TUBE_CORAL_BLOCK = Blocks::TUBE_CORAL_BLOCK->getDefaultState();
    BRAIN_CORAL_BLOCK = Blocks::BRAIN_CORAL_BLOCK->getDefaultState();
    BUBBLE_CORAL_BLOCK = Blocks::BUBBLE_CORAL_BLOCK->getDefaultState();
    FIRE_CORAL_BLOCK = Blocks::FIRE_CORAL_BLOCK->getDefaultState();
    HORN_CORAL_BLOCK = Blocks::HORN_CORAL_BLOCK->getDefaultState();
    DEAD_TUBE_CORAL = Blocks::DEAD_TUBE_CORAL->getDefaultState();
    DEAD_BRAIN_CORAL = Blocks::DEAD_BRAIN_CORAL->getDefaultState();
    DEAD_BUBBLE_CORAL = Blocks::DEAD_BUBBLE_CORAL->getDefaultState();
    DEAD_FIRE_CORAL = Blocks::DEAD_FIRE_CORAL->getDefaultState();
    DEAD_HORN_CORAL = Blocks::DEAD_HORN_CORAL->getDefaultState();
    TUBE_CORAL = Blocks::TUBE_CORAL->getDefaultState();
    BRAIN_CORAL = Blocks::BRAIN_CORAL->getDefaultState();
    BUBBLE_CORAL = Blocks::BUBBLE_CORAL->getDefaultState();
    FIRE_CORAL = Blocks::FIRE_CORAL->getDefaultState();
    HORN_CORAL = Blocks::HORN_CORAL->getDefaultState();
    DEAD_TUBE_CORAL_FAN = Blocks::DEAD_TUBE_CORAL_FAN->getDefaultState();
    DEAD_BRAIN_CORAL_FAN = Blocks::DEAD_BRAIN_CORAL_FAN->getDefaultState();
    DEAD_BUBBLE_CORAL_FAN = Blocks::DEAD_BUBBLE_CORAL_FAN->getDefaultState();
    DEAD_FIRE_CORAL_FAN = Blocks::DEAD_FIRE_CORAL_FAN->getDefaultState();
    DEAD_HORN_CORAL_FAN = Blocks::DEAD_HORN_CORAL_FAN->getDefaultState();
    TUBE_CORAL_FAN = Blocks::TUBE_CORAL_FAN->getDefaultState();
    BRAIN_CORAL_FAN = Blocks::BRAIN_CORAL_FAN->getDefaultState();
    BUBBLE_CORAL_FAN = Blocks::BUBBLE_CORAL_FAN->getDefaultState();
    FIRE_CORAL_FAN = Blocks::FIRE_CORAL_FAN->getDefaultState();
    HORN_CORAL_FAN = Blocks::HORN_CORAL_FAN->getDefaultState();
    DEAD_TUBE_CORAL_WALL_FAN = Blocks::DEAD_TUBE_CORAL_WALL_FAN->getDefaultState();
    DEAD_BRAIN_CORAL_WALL_FAN = Blocks::DEAD_BRAIN_CORAL_WALL_FAN->getDefaultState();
    DEAD_BUBBLE_CORAL_WALL_FAN = Blocks::DEAD_BUBBLE_CORAL_WALL_FAN->getDefaultState();
    DEAD_FIRE_CORAL_WALL_FAN = Blocks::DEAD_FIRE_CORAL_WALL_FAN->getDefaultState();
    DEAD_HORN_CORAL_WALL_FAN = Blocks::DEAD_HORN_CORAL_WALL_FAN->getDefaultState();
    TUBE_CORAL_WALL_FAN = Blocks::TUBE_CORAL_WALL_FAN->getDefaultState();
    BRAIN_CORAL_WALL_FAN = Blocks::BRAIN_CORAL_WALL_FAN->getDefaultState();
    BUBBLE_CORAL_WALL_FAN = Blocks::BUBBLE_CORAL_WALL_FAN->getDefaultState();
    FIRE_CORAL_WALL_FAN = Blocks::FIRE_CORAL_WALL_FAN->getDefaultState();
    HORN_CORAL_WALL_FAN = Blocks::HORN_CORAL_WALL_FAN->getDefaultState();
    SEA_PICKLE = Blocks::SEA_PICKLE->getDefaultState();
    BLUE_ICE = Blocks::BLUE_ICE->getDefaultState();
    CONDUIT = Blocks::CONDUIT->getDefaultState();
    BAMBOO_SAPLING = Blocks::BAMBOO_SAPLING->getDefaultState();
    BAMBOO = Blocks::BAMBOO->getDefaultState();
    POTTED_BAMBOO = Blocks::POTTED_BAMBOO->getDefaultState();
    VOID_AIR = Blocks::VOID_AIR->getDefaultState();
    CAVE_AIR = Blocks::CAVE_AIR->getDefaultState();
    BUBBLE_COLUMN = Blocks::BUBBLE_COLUMN->getDefaultState();
    POLISHED_GRANITE_STAIRS = Blocks::POLISHED_GRANITE_STAIRS->getDefaultState();
    SMOOTH_RED_SANDSTONE_STAIRS = Blocks::SMOOTH_RED_SANDSTONE_STAIRS->getDefaultState();
    MOSSY_STONE_BRICK_STAIRS = Blocks::MOSSY_STONE_BRICK_STAIRS->getDefaultState();
    POLISHED_DIORITE_STAIRS = Blocks::POLISHED_DIORITE_STAIRS->getDefaultState();
    MOSSY_COBBLESTONE_STAIRS = Blocks::MOSSY_COBBLESTONE_STAIRS->getDefaultState();
    END_STONE_BRICK_STAIRS = Blocks::END_STONE_BRICK_STAIRS->getDefaultState();
    STONE_STAIRS = Blocks::STONE_STAIRS->getDefaultState();
    SMOOTH_SANDSTONE_STAIRS = Blocks::SMOOTH_SANDSTONE_STAIRS->getDefaultState();
    SMOOTH_QUARTZ_STAIRS = Blocks::SMOOTH_QUARTZ_STAIRS->getDefaultState();
    GRANITE_STAIRS = Blocks::GRANITE_STAIRS->getDefaultState();
    ANDESITE_STAIRS = Blocks::ANDESITE_STAIRS->getDefaultState();
    RED_NETHER_BRICK_STAIRS = Blocks::RED_NETHER_BRICK_STAIRS->getDefaultState();
    POLISHED_ANDESITE_STAIRS = Blocks::POLISHED_ANDESITE_STAIRS->getDefaultState();
    DIORITE_STAIRS = Blocks::DIORITE_STAIRS->getDefaultState();
    POLISHED_GRANITE_SLAB = Blocks::POLISHED_GRANITE_SLAB->getDefaultState();
    SMOOTH_RED_SANDSTONE_SLAB = Blocks::SMOOTH_RED_SANDSTONE_SLAB->getDefaultState();
    MOSSY_STONE_BRICK_SLAB = Blocks::MOSSY_STONE_BRICK_SLAB->getDefaultState();
    POLISHED_DIORITE_SLAB = Blocks::POLISHED_DIORITE_SLAB->getDefaultState();
    MOSSY_COBBLESTONE_SLAB = Blocks::MOSSY_COBBLESTONE_SLAB->getDefaultState();
    END_STONE_BRICK_SLAB = Blocks::END_STONE_BRICK_SLAB->getDefaultState();
    SMOOTH_SANDSTONE_SLAB = Blocks::SMOOTH_SANDSTONE_SLAB->getDefaultState();
    SMOOTH_QUARTZ_SLAB = Blocks::SMOOTH_QUARTZ_SLAB->getDefaultState();
    GRANITE_SLAB = Blocks::GRANITE_SLAB->getDefaultState();
    ANDESITE_SLAB = Blocks::ANDESITE_SLAB->getDefaultState();
    RED_NETHER_BRICK_SLAB = Blocks::RED_NETHER_BRICK_SLAB->getDefaultState();
    POLISHED_ANDESITE_SLAB = Blocks::POLISHED_ANDESITE_SLAB->getDefaultState();
    DIORITE_SLAB = Blocks::DIORITE_SLAB->getDefaultState();
    BRICK_WALL = Blocks::BRICK_WALL->getDefaultState();
    PRISMARINE_WALL = Blocks::PRISMARINE_WALL->getDefaultState();
    RED_SANDSTONE_WALL = Blocks::RED_SANDSTONE_WALL->getDefaultState();
    MOSSY_STONE_BRICK_WALL = Blocks::MOSSY_STONE_BRICK_WALL->getDefaultState();
    GRANITE_WALL = Blocks::GRANITE_WALL->getDefaultState();
    STONE_BRICK_WALL = Blocks::STONE_BRICK_WALL->getDefaultState();
    NETHER_BRICK_WALL = Blocks::NETHER_BRICK_WALL->getDefaultState();
    ANDESITE_WALL = Blocks::ANDESITE_WALL->getDefaultState();
    RED_NETHER_BRICK_WALL = Blocks::RED_NETHER_BRICK_WALL->getDefaultState();
    SANDSTONE_WALL = Blocks::SANDSTONE_WALL->getDefaultState();
    END_STONE_BRICK_WALL = Blocks::END_STONE_BRICK_WALL->getDefaultState();
    DIORITE_WALL = Blocks::DIORITE_WALL->getDefaultState();
    SCAFFOLDING = Blocks::SCAFFOLDING->getDefaultState();
    LOOM = Blocks::LOOM->getDefaultState();
    BARREL = Blocks::BARREL->getDefaultState();
    SMOKER = Blocks::SMOKER->getDefaultState();
    BLAST_FURNACE = Blocks::BLAST_FURNACE->getDefaultState();
    CARTOGRAPHY_TABLE = Blocks::CARTOGRAPHY_TABLE->getDefaultState();
    FLETCHING_TABLE = Blocks::FLETCHING_TABLE->getDefaultState();
    GRINDSTONE = Blocks::GRINDSTONE->getDefaultState();
    LECTERN = Blocks::LECTERN->getDefaultState();
    SMITHING_TABLE = Blocks::SMITHING_TABLE->getDefaultState();
    STONECUTTER = Blocks::STONECUTTER->getDefaultState();
    BELL = Blocks::BELL->getDefaultState();
    LANTERN = Blocks::LANTERN->getDefaultState();
    SOUL_LANTERN = Blocks::SOUL_LANTERN->getDefaultState();
    CAMPFIRE = Blocks::CAMPFIRE->getDefaultState();
    SOUL_CAMPFIRE = Blocks::SOUL_CAMPFIRE->getDefaultState();
    SWEET_BERRY_BUSH = Blocks::SWEET_BERRY_BUSH->getDefaultState();
    WARPED_STEM = Blocks::WARPED_STEM->getDefaultState();
    STRIPPED_WARPED_STEM = Blocks::STRIPPED_WARPED_STEM->getDefaultState();
    WARPED_HYPHAE = Blocks::WARPED_HYPHAE->getDefaultState();
    STRIPPED_WARPED_HYPHAE = Blocks::STRIPPED_WARPED_HYPHAE->getDefaultState();
    WARPED_NYLIUM = Blocks::WARPED_NYLIUM->getDefaultState();
    WARPED_FUNGUS = Blocks::WARPED_FUNGUS->getDefaultState();
    WARPED_WART_BLOCK = Blocks::WARPED_WART_BLOCK->getDefaultState();
    WARPED_ROOTS = Blocks::WARPED_ROOTS->getDefaultState();
    NETHER_SPROUTS = Blocks::NETHER_SPROUTS->getDefaultState();
    CRIMSON_STEM = Blocks::CRIMSON_STEM->getDefaultState();
    STRIPPED_CRIMSON_STEM = Blocks::STRIPPED_CRIMSON_STEM->getDefaultState();
    CRIMSON_HYPHAE = Blocks::CRIMSON_HYPHAE->getDefaultState();
    STRIPPED_CRIMSON_HYPHAE = Blocks::STRIPPED_CRIMSON_HYPHAE->getDefaultState();
    CRIMSON_NYLIUM = Blocks::CRIMSON_NYLIUM->getDefaultState();
    CRIMSON_FUNGUS = Blocks::CRIMSON_FUNGUS->getDefaultState();
    SHROOMLIGHT = Blocks::SHROOMLIGHT->getDefaultState();
    WEEPING_VINES = Blocks::WEEPING_VINES->getDefaultState();
    WEEPING_VINES_PLANT = Blocks::WEEPING_VINES_PLANT->getDefaultState();
    TWISTING_VINES = Blocks::TWISTING_VINES->getDefaultState();
    TWISTING_VINES_PLANT = Blocks::TWISTING_VINES_PLANT->getDefaultState();
    CRIMSON_ROOTS = Blocks::CRIMSON_ROOTS->getDefaultState();
    CRIMSON_PLANKS = Blocks::CRIMSON_PLANKS->getDefaultState();
    WARPED_PLANKS = Blocks::WARPED_PLANKS->getDefaultState();
    CRIMSON_SLAB = Blocks::CRIMSON_SLAB->getDefaultState();
    WARPED_SLAB = Blocks::WARPED_SLAB->getDefaultState();
    CRIMSON_PRESSURE_PLATE = Blocks::CRIMSON_PRESSURE_PLATE->getDefaultState();
    WARPED_PRESSURE_PLATE = Blocks::WARPED_PRESSURE_PLATE->getDefaultState();
    CRIMSON_FENCE = Blocks::CRIMSON_FENCE->getDefaultState();
    WARPED_FENCE = Blocks::WARPED_FENCE->getDefaultState();
    CRIMSON_TRAPDOOR = Blocks::CRIMSON_TRAPDOOR->getDefaultState();
    WARPED_TRAPDOOR = Blocks::WARPED_TRAPDOOR->getDefaultState();
    CRIMSON_FENCE_GATE = Blocks::CRIMSON_FENCE_GATE->getDefaultState();
    WARPED_FENCE_GATE = Blocks::WARPED_FENCE_GATE->getDefaultState();
    CRIMSON_STAIRS = Blocks::CRIMSON_STAIRS->getDefaultState();
    WARPED_STAIRS = Blocks::WARPED_STAIRS->getDefaultState();
    CRIMSON_BUTTON = Blocks::CRIMSON_BUTTON->getDefaultState();
    WARPED_BUTTON = Blocks::WARPED_BUTTON->getDefaultState();
    CRIMSON_DOOR = Blocks::CRIMSON_DOOR->getDefaultState();
    WARPED_DOOR = Blocks::WARPED_DOOR->getDefaultState();
    CRIMSON_SIGN = Blocks::CRIMSON_SIGN->getDefaultState();
    WARPED_SIGN = Blocks::WARPED_SIGN->getDefaultState();
    CRIMSON_WALL_SIGN = Blocks::CRIMSON_WALL_SIGN->getDefaultState();
    WARPED_WALL_SIGN = Blocks::WARPED_WALL_SIGN->getDefaultState();
    STRUCTURE_BLOCK = Blocks::STRUCTURE_BLOCK->getDefaultState();
    JIGSAW = Blocks::JIGSAW->getDefaultState();
    COMPOSTER = Blocks::COMPOSTER->getDefaultState();
    TARGET = Blocks::TARGET->getDefaultState();
    BEE_NEST = Blocks::BEE_NEST->getDefaultState();
    BEEHIVE = Blocks::BEEHIVE->getDefaultState();
    HONEY_BLOCK = Blocks::HONEY_BLOCK->getDefaultState();
    HONEYCOMB_BLOCK = Blocks::HONEYCOMB_BLOCK->getDefaultState();
    NETHERITE_BLOCK = Blocks::NETHERITE_BLOCK->getDefaultState();
    ANCIENT_DEBRIS = Blocks::ANCIENT_DEBRIS->getDefaultState();
    CRYING_OBSIDIAN = Blocks::CRYING_OBSIDIAN->getDefaultState();
    RESPAWN_ANCHOR = Blocks::RESPAWN_ANCHOR->getDefaultState();
    POTTED_CRIMSON_FUNGUS = Blocks::POTTED_CRIMSON_FUNGUS->getDefaultState();
    POTTED_WARPED_FUNGUS = Blocks::POTTED_WARPED_FUNGUS->getDefaultState();
    POTTED_CRIMSON_ROOTS = Blocks::POTTED_CRIMSON_ROOTS->getDefaultState();
    POTTED_WARPED_ROOTS = Blocks::POTTED_WARPED_ROOTS->getDefaultState();
    LODESTONE = Blocks::LODESTONE->getDefaultState();
    BLACKSTONE = Blocks::BLACKSTONE->getDefaultState();
    BLACKSTONE_STAIRS = Blocks::BLACKSTONE_STAIRS->getDefaultState();
    BLACKSTONE_WALL = Blocks::BLACKSTONE_WALL->getDefaultState();
    BLACKSTONE_SLAB = Blocks::BLACKSTONE_SLAB->getDefaultState();
    POLISHED_BLACKSTONE = Blocks::POLISHED_BLACKSTONE->getDefaultState();
    POLISHED_BLACKSTONE_BRICKS = Blocks::POLISHED_BLACKSTONE_BRICKS->getDefaultState();
    CRACKED_POLISHED_BLACKSTONE_BRICKS = Blocks::CRACKED_POLISHED_BLACKSTONE_BRICKS->getDefaultState();
    CHISELED_POLISHED_BLACKSTONE = Blocks::CHISELED_POLISHED_BLACKSTONE->getDefaultState();
    POLISHED_BLACKSTONE_BRICK_SLAB = Blocks::POLISHED_BLACKSTONE_BRICK_SLAB->getDefaultState();
    POLISHED_BLACKSTONE_BRICK_STAIRS = Blocks::POLISHED_BLACKSTONE_BRICK_STAIRS->getDefaultState();
    POLISHED_BLACKSTONE_BRICK_WALL = Blocks::POLISHED_BLACKSTONE_BRICK_WALL->getDefaultState();
    GILDED_BLACKSTONE = Blocks::GILDED_BLACKSTONE->getDefaultState();
    POLISHED_BLACKSTONE_STAIRS = Blocks::POLISHED_BLACKSTONE_STAIRS->getDefaultState();
    POLISHED_BLACKSTONE_SLAB = Blocks::POLISHED_BLACKSTONE_SLAB->getDefaultState();
    POLISHED_BLACKSTONE_PRESSURE_PLATE = Blocks::POLISHED_BLACKSTONE_PRESSURE_PLATE->getDefaultState();
    POLISHED_BLACKSTONE_BUTTON = Blocks::POLISHED_BLACKSTONE_BUTTON->getDefaultState();
    POLISHED_BLACKSTONE_WALL = Blocks::POLISHED_BLACKSTONE_WALL->getDefaultState();
    CHISELED_NETHER_BRICKS = Blocks::CHISELED_NETHER_BRICKS->getDefaultState();
    CRACKED_NETHER_BRICKS = Blocks::CRACKED_NETHER_BRICKS->getDefaultState();
    QUARTZ_BRICKS = Blocks::QUARTZ_BRICKS->getDefaultState();
}