#include "Block.hpp"


std::vector<Block*> Block::id_to_block;
std::vector<Block*> Block::block_to_id;

Block* Block::acacia_button = nullptr;
Block* Block::acacia_door = nullptr;
Block* Block::acacia_fence_gate = nullptr;
Block* Block::acacia_pressure_plate = nullptr;
Block* Block::acacia_stairs = nullptr;
Block* Block::acacia_standing_sign = nullptr;
Block* Block::acacia_trapdoor = nullptr;
Block* Block::acacia_wall_sign = nullptr;
Block* Block::activator_rail = nullptr;
Block* Block::air = nullptr;
Block* Block::allow = nullptr;
Block* Block::andesite_stairs = nullptr;
Block* Block::anvil = nullptr;
Block* Block::bamboo = nullptr;
Block* Block::bamboo_sapling = nullptr;
Block* Block::barrel = nullptr;
Block* Block::barrier = nullptr;
Block* Block::beacon = nullptr;
Block* Block::bed = nullptr;
Block* Block::bedrock = nullptr;
Block* Block::beetroot = nullptr;
Block* Block::bell = nullptr;
Block* Block::birch_button = nullptr;
Block* Block::birch_door = nullptr;
Block* Block::birch_fence_gate = nullptr;
Block* Block::birch_pressure_plate = nullptr;
Block* Block::birch_stairs = nullptr;
Block* Block::birch_standing_sign = nullptr;
Block* Block::birch_trapdoor = nullptr;
Block* Block::birch_wall_sign = nullptr;
Block* Block::black_glazed_terracotta = nullptr;
Block* Block::blast_furnace = nullptr;
Block* Block::blue_glazed_terracotta = nullptr;
Block* Block::blue_ice = nullptr;
Block* Block::bone_block = nullptr;
Block* Block::bookshelf = nullptr;
Block* Block::border_block = nullptr;
Block* Block::brewing_stand = nullptr;
Block* Block::brick_block = nullptr;
Block* Block::brick_stairs = nullptr;
Block* Block::brown_glazed_terracotta = nullptr;
Block* Block::brown_mushroom = nullptr;
Block* Block::brown_mushroom_block = nullptr;
Block* Block::bubble_column = nullptr;
Block* Block::cactus = nullptr;
Block* Block::cake = nullptr;
Block* Block::camera = nullptr;
Block* Block::campfire = nullptr;
Block* Block::carpet = nullptr;
Block* Block::carrots = nullptr;
Block* Block::cartography_table = nullptr;
Block* Block::carved_pumpkin = nullptr;
Block* Block::cauldron = nullptr;
Block* Block::chain_command_block = nullptr;
Block* Block::chest = nullptr;
Block* Block::chorus_flower = nullptr;
Block* Block::chorus_plant = nullptr;
Block* Block::clay = nullptr;
Block* Block::coal_block = nullptr;
Block* Block::coal_ore = nullptr;
Block* Block::cobblestone = nullptr;
Block* Block::cobblestone_wall = nullptr;
Block* Block::cocoa = nullptr;
Block* Block::command_block = nullptr;
Block* Block::composter = nullptr;
Block* Block::concrete = nullptr;
Block* Block::concretePowder = nullptr;
Block* Block::conduit = nullptr;
Block* Block::coral = nullptr;
Block* Block::coral_block = nullptr;
Block* Block::coral_fan = nullptr;
Block* Block::coral_fan_dead = nullptr;
Block* Block::coral_fan_hang = nullptr;
Block* Block::coral_fan_hang2 = nullptr;
Block* Block::coral_fan_hang3 = nullptr;
Block* Block::crafting_table = nullptr;
Block* Block::cyan_glazed_terracotta = nullptr;
Block* Block::dark_oak_button = nullptr;
Block* Block::dark_oak_door = nullptr;
Block* Block::dark_oak_fence_gate = nullptr;
Block* Block::dark_oak_pressure_plate = nullptr;
Block* Block::dark_oak_stairs = nullptr;
Block* Block::dark_oak_trapdoor = nullptr;
Block* Block::dark_prismarine_stairs = nullptr;
Block* Block::darkoak_standing_sign = nullptr;
Block* Block::darkoak_wall_sign = nullptr;
Block* Block::daylight_detector = nullptr;
Block* Block::daylight_detector_inverted = nullptr;
Block* Block::deadbush = nullptr;
Block* Block::deny = nullptr;
Block* Block::detector_rail = nullptr;
Block* Block::diamond_block = nullptr;
Block* Block::diamond_ore = nullptr;
Block* Block::diorite_stairs = nullptr;
Block* Block::dirt = nullptr;
Block* Block::dispenser = nullptr;
Block* Block::double_plant = nullptr;
Block* Block::double_stone_slab = nullptr;
Block* Block::double_stone_slab2 = nullptr;
Block* Block::double_stone_slab3 = nullptr;
Block* Block::double_stone_slab4 = nullptr;
Block* Block::double_wooden_slab = nullptr;
Block* Block::dragon_egg = nullptr;
Block* Block::dried_kelp_block = nullptr;
Block* Block::dropper = nullptr;
Block* Block::emerald_block = nullptr;
Block* Block::emerald_ore = nullptr;
Block* Block::enchanting_table = nullptr;
Block* Block::end_brick_stairs = nullptr;
Block* Block::end_bricks = nullptr;
Block* Block::end_gateway = nullptr;
Block* Block::end_portal = nullptr;
Block* Block::end_portal_frame = nullptr;
Block* Block::end_rod = nullptr;
Block* Block::end_stone = nullptr;
Block* Block::ender_chest = nullptr;
Block* Block::farmland = nullptr;
Block* Block::fence = nullptr;
Block* Block::fence_gate = nullptr;
Block* Block::fire = nullptr;
Block* Block::fletching_table = nullptr;
Block* Block::flower_pot = nullptr;
LiquidBlock* Block::flowing_lava = nullptr;
LiquidBlock* Block::flowing_water = nullptr;
Block* Block::frame = nullptr;
Block* Block::frosted_ice = nullptr;
Block* Block::furnace = nullptr;
Block* Block::glass = nullptr;
Block* Block::glass_pane = nullptr;
Block* Block::glowingobsidian = nullptr;
Block* Block::glowstone = nullptr;
Block* Block::gold_block = nullptr;
Block* Block::gold_ore = nullptr;
Block* Block::golden_rail = nullptr;
Block* Block::granite_stairs = nullptr;
Block* Block::grass = nullptr;
Block* Block::grass_path = nullptr;
Block* Block::gravel = nullptr;
Block* Block::gray_glazed_terracotta = nullptr;
Block* Block::green_glazed_terracotta = nullptr;
Block* Block::grindstone = nullptr;
Block* Block::hardened_clay = nullptr;
Block* Block::hay_block = nullptr;
Block* Block::heavy_weighted_pressure_plate = nullptr;
Block* Block::hopper = nullptr;
Block* Block::ice = nullptr;
Block* Block::info_update = nullptr;
Block* Block::info_update2 = nullptr;
Block* Block::invisibleBedrock = nullptr;
Block* Block::iron_bars = nullptr;
Block* Block::iron_block = nullptr;
Block* Block::iron_door = nullptr;
Block* Block::iron_ore = nullptr;
Block* Block::iron_trapdoor = nullptr;
Block* Block::jigsaw = nullptr;
Block* Block::jukebox = nullptr;
Block* Block::jungle_button = nullptr;
Block* Block::jungle_door = nullptr;
Block* Block::jungle_fence_gate = nullptr;
Block* Block::jungle_pressure_plate = nullptr;
Block* Block::jungle_stairs = nullptr;
Block* Block::jungle_standing_sign = nullptr;
Block* Block::jungle_trapdoor = nullptr;
Block* Block::jungle_wall_sign = nullptr;
Block* Block::kelp = nullptr;
Block* Block::ladder = nullptr;
Block* Block::lantern = nullptr;
Block* Block::lapis_block = nullptr;
Block* Block::lapis_ore = nullptr;
LiquidBlock* Block::lava = nullptr;
Block* Block::lava_cauldron = nullptr;
Block* Block::leaves = nullptr;
Block* Block::leaves2 = nullptr;
Block* Block::lectern = nullptr;
Block* Block::lever = nullptr;
Block* Block::light_block = nullptr;
Block* Block::light_blue_glazed_terracotta = nullptr;
Block* Block::light_weighted_pressure_plate = nullptr;
Block* Block::lime_glazed_terracotta = nullptr;
Block* Block::lit_blast_furnace = nullptr;
Block* Block::lit_furnace = nullptr;
Block* Block::lit_pumpkin = nullptr;
Block* Block::lit_redstone_lamp = nullptr;
Block* Block::lit_redstone_ore = nullptr;
Block* Block::lit_smoker = nullptr;
Block* Block::log = nullptr;
Block* Block::log2 = nullptr;
Block* Block::loom = nullptr;
Block* Block::magenta_glazed_terracotta = nullptr;
Block* Block::magma = nullptr;
Block* Block::melon_block = nullptr;
Block* Block::melon_stem = nullptr;
Block* Block::mob_spawner = nullptr;
Block* Block::monster_egg = nullptr;
Block* Block::mossy_cobblestone = nullptr;
Block* Block::mossy_cobblestone_stairs = nullptr;
Block* Block::mossy_stone_brick_stairs = nullptr;
Block* Block::movingBlock = nullptr;
Block* Block::mycelium = nullptr;
Block* Block::nether_brick = nullptr;
Block* Block::nether_brick_fence = nullptr;
Block* Block::nether_brick_stairs = nullptr;
Block* Block::nether_wart = nullptr;
Block* Block::nether_wart_block = nullptr;
Block* Block::netherrack = nullptr;
Block* Block::netherreactor = nullptr;
Block* Block::normal_stone_stairs = nullptr;
Block* Block::noteblock = nullptr;
Block* Block::oak_stairs = nullptr;
Block* Block::observer = nullptr;
Block* Block::obsidian = nullptr;
Block* Block::orange_glazed_terracotta = nullptr;
Block* Block::packed_ice = nullptr;
Block* Block::pink_glazed_terracotta = nullptr;
Block* Block::piston = nullptr;
Block* Block::pistonArmCollision = nullptr;
Block* Block::planks = nullptr;
Block* Block::podzol = nullptr;
Block* Block::polished_andesite_stairs = nullptr;
Block* Block::polished_diorite_stairs = nullptr;
Block* Block::polished_granite_stairs = nullptr;
Block* Block::portal = nullptr;
Block* Block::potatoes = nullptr;
Block* Block::powered_comparator = nullptr;
Block* Block::powered_repeater = nullptr;
Block* Block::prismarine = nullptr;
Block* Block::prismarine_bricks_stairs = nullptr;
Block* Block::prismarine_stairs = nullptr;
Block* Block::pumpkin = nullptr;
Block* Block::pumpkin_stem = nullptr;
Block* Block::purple_glazed_terracotta = nullptr;
Block* Block::purpur_block = nullptr;
Block* Block::purpur_stairs = nullptr;
Block* Block::quartz_block = nullptr;
Block* Block::quartz_ore = nullptr;
Block* Block::quartz_stairs = nullptr;
Block* Block::rail = nullptr;
Block* Block::red_flower = nullptr;
Block* Block::red_glazed_terracotta = nullptr;
Block* Block::red_mushroom = nullptr;
Block* Block::red_mushroom_block = nullptr;
Block* Block::red_nether_brick = nullptr;
Block* Block::red_nether_brick_stairs = nullptr;
Block* Block::red_sandstone = nullptr;
Block* Block::red_sandstone_stairs = nullptr;
Block* Block::redstone_block = nullptr;
Block* Block::redstone_lamp = nullptr;
Block* Block::redstone_ore = nullptr;
Block* Block::redstone_torch = nullptr;
Block* Block::redstone_wire = nullptr;
Block* Block::reeds = nullptr;
Block* Block::repeating_command_block = nullptr;
Block* Block::reserved6 = nullptr;
Block* Block::sand = nullptr;
Block* Block::sandstone = nullptr;
Block* Block::sandstone_stairs = nullptr;
Block* Block::sapling = nullptr;
Block* Block::scaffolding = nullptr;
Block* Block::seaLantern = nullptr;
Block* Block::sea_pickle = nullptr;
Block* Block::seagrass = nullptr;
Block* Block::shulker_box = nullptr;
Block* Block::silver_glazed_terracotta = nullptr;
Block* Block::skull = nullptr;
Block* Block::slime = nullptr;
Block* Block::smithing_table = nullptr;
Block* Block::smoker = nullptr;
Block* Block::smooth_quartz_stairs = nullptr;
Block* Block::smooth_red_sandstone_stairs = nullptr;
Block* Block::smooth_sandstone_stairs = nullptr;
Block* Block::smooth_stone = nullptr;
Block* Block::snow = nullptr;
Block* Block::snow_layer = nullptr;
Block* Block::soul_sand = nullptr;
Block* Block::sponge = nullptr;
Block* Block::spruce_button = nullptr;
Block* Block::spruce_door = nullptr;
Block* Block::spruce_fence_gate = nullptr;
Block* Block::spruce_pressure_plate = nullptr;
Block* Block::spruce_stairs = nullptr;
Block* Block::spruce_standing_sign = nullptr;
Block* Block::spruce_trapdoor = nullptr;
Block* Block::spruce_wall_sign = nullptr;
Block* Block::stained_glass = nullptr;
Block* Block::stained_glass_pane = nullptr;
Block* Block::stained_hardened_clay = nullptr;
Block* Block::standing_banner = nullptr;
Block* Block::standing_sign = nullptr;
Block* Block::stickyPistonArmCollision = nullptr;
Block* Block::sticky_piston = nullptr;
Block* Block::stone = nullptr;
Block* Block::stone_brick_stairs = nullptr;
Block* Block::stone_button = nullptr;
Block* Block::stone_pressure_plate = nullptr;
Block* Block::stone_slab = nullptr;
Block* Block::stone_slab2 = nullptr;
Block* Block::stone_slab3 = nullptr;
Block* Block::stone_slab4 = nullptr;
Block* Block::stone_stairs = nullptr;
Block* Block::stonebrick = nullptr;
Block* Block::stonecutter = nullptr;
Block* Block::stonecutter_block = nullptr;
Block* Block::stripped_acacia_log = nullptr;
Block* Block::stripped_birch_log = nullptr;
Block* Block::stripped_dark_oak_log = nullptr;
Block* Block::stripped_jungle_log = nullptr;
Block* Block::stripped_oak_log = nullptr;
Block* Block::stripped_spruce_log = nullptr;
Block* Block::structure_block = nullptr;
Block* Block::structure_void = nullptr;
Block* Block::sweet_berry_bush = nullptr;
Block* Block::tallgrass = nullptr;
Block* Block::tnt = nullptr;
Block* Block::torch = nullptr;
Block* Block::trapdoor = nullptr;
Block* Block::trapped_chest = nullptr;
Block* Block::tripWire = nullptr;
Block* Block::tripwire_hook = nullptr;
Block* Block::turtle_egg = nullptr;
Block* Block::undyed_shulker_box = nullptr;
Block* Block::unlit_redstone_torch = nullptr;
Block* Block::unpowered_comparator = nullptr;
Block* Block::unpowered_repeater = nullptr;
Block* Block::vine = nullptr;
Block* Block::wall_banner = nullptr;
Block* Block::wall_sign = nullptr;
LiquidBlock* Block::water = nullptr;
Block* Block::waterlily = nullptr;
Block* Block::web = nullptr;
Block* Block::wheat = nullptr;
Block* Block::white_glazed_terracotta = nullptr;
Block* Block::wither_rose = nullptr;
Block* Block::wood = nullptr;
Block* Block::wooden_button = nullptr;
Block* Block::wooden_door = nullptr;
Block* Block::wooden_pressure_plate = nullptr;
Block* Block::wooden_slab = nullptr;
Block* Block::wool = nullptr;
Block* Block::yellow_flower = nullptr;
Block* Block::yellow_glazed_terracotta = nullptr;

void Block::initBlocks() {
	acacia_button = new Block("acacia_button");
	acacia_door = new Block("acacia_door");
	acacia_fence_gate = new Block("acacia_fence_gate");
	acacia_pressure_plate = new Block("acacia_pressure_plate");
	acacia_stairs = new Block("acacia_stairs");
	acacia_standing_sign = new Block("acacia_standing_sign");
	acacia_trapdoor = new Block("acacia_trapdoor");
	acacia_wall_sign = new Block("acacia_wall_sign");
	activator_rail = new Block("activator_rail");
	air = (new Block("air"))->setRenderType(RenderType::Air);
	allow = new Block("allow");
	andesite_stairs = new Block("andesite_stairs");
	anvil = new Block("anvil");
	bamboo = new Block("bamboo");
	bamboo_sapling = new Block("bamboo_sapling");
	barrel = new Block("barrel");
	barrier = new Block("barrier");
	beacon = new Block("beacon");
	bed = new Block("bed");
	bedrock = new Block("bedrock");
	beetroot = new Block("beetroot");
	bell = new Block("bell");
	birch_button = new Block("birch_button");
	birch_door = new Block("birch_door");
	birch_fence_gate = new Block("birch_fence_gate");
	birch_pressure_plate = new Block("birch_pressure_plate");
	birch_stairs = new Block("birch_stairs");
	birch_standing_sign = new Block("birch_standing_sign");
	birch_trapdoor = new Block("birch_trapdoor");
	birch_wall_sign = new Block("birch_wall_sign");
	black_glazed_terracotta = new Block("black_glazed_terracotta");
	blast_furnace = new Block("blast_furnace");
	blue_glazed_terracotta = new Block("blue_glazed_terracotta");
	blue_ice = new Block("blue_ice");
	bone_block = new Block("bone_block");
	bookshelf = new Block("bookshelf");
	border_block = new Block("border_block");
	brewing_stand = new Block("brewing_stand");
	brick_block = new Block("brick_block");
	brick_stairs = new Block("brick_stairs");
	brown_glazed_terracotta = new Block("brown_glazed_terracotta");
	brown_mushroom = new Block("brown_mushroom");
	brown_mushroom_block = new Block("brown_mushroom_block");
	bubble_column = new Block("bubble_column");
	cactus = new Block("cactus");
	cake = new Block("cake");
	camera = new Block("camera");
	campfire = new Block("campfire");
	carpet = new Block("carpet");
	carrots = new Block("carrots");
	cartography_table = new Block("cartography_table");
	carved_pumpkin = new Block("carved_pumpkin");
	cauldron = new Block("cauldron");
	chain_command_block = new Block("chain_command_block");
	chest = new Block("chest");
	chorus_flower = new Block("chorus_flower");
	chorus_plant = new Block("chorus_plant");
	clay = new Block("clay");
	coal_block = new Block("coal_block");
	coal_ore = new Block("coal_ore");
	cobblestone = new Block("cobblestone");
	cobblestone_wall = new Block("cobblestone_wall");
	cocoa = new Block("cocoa");
	command_block = new Block("command_block");
	composter = new Block("composter");
	concrete = new Block("concrete");
	concretePowder = new Block("concretePowder");
	conduit = new Block("conduit");
	coral = new Block("coral");
	coral_block = new Block("coral_block");
	coral_fan = new Block("coral_fan");
	coral_fan_dead = new Block("coral_fan_dead");
	coral_fan_hang = new Block("coral_fan_hang");
	coral_fan_hang2 = new Block("coral_fan_hang2");
	coral_fan_hang3 = new Block("coral_fan_hang3");
	crafting_table = new Block("crafting_table");
	cyan_glazed_terracotta = new Block("cyan_glazed_terracotta");
	dark_oak_button = new Block("dark_oak_button");
	dark_oak_door = new Block("dark_oak_door");
	dark_oak_fence_gate = new Block("dark_oak_fence_gate");
	dark_oak_pressure_plate = new Block("dark_oak_pressure_plate");
	dark_oak_stairs = new Block("dark_oak_stairs");
	dark_oak_trapdoor = new Block("dark_oak_trapdoor");
	dark_prismarine_stairs = new Block("dark_prismarine_stairs");
	darkoak_standing_sign = new Block("darkoak_standing_sign");
	darkoak_wall_sign = new Block("darkoak_wall_sign");
	daylight_detector = new Block("daylight_detector");
	daylight_detector_inverted = new Block("daylight_detector_inverted");
	deadbush = new Block("deadbush");
	deny = new Block("deny");
	detector_rail = new Block("detector_rail");
	diamond_block = new Block("diamond_block");
	diamond_ore = new Block("diamond_ore");
	diorite_stairs = new Block("diorite_stairs");
	dirt = new Block("dirt");
	dispenser = new Block("dispenser");
	double_plant = (new Block("double_plant"))->setRenderType(RenderType::Cross)->setTint(Tint::Grass);
	double_stone_slab = new Block("double_stone_slab");
	double_stone_slab2 = new Block("double_stone_slab2");
	double_stone_slab3 = new Block("double_stone_slab3");
	double_stone_slab4 = new Block("double_stone_slab4");
	double_wooden_slab = new Block("double_wooden_slab");
	dragon_egg = new Block("dragon_egg");
	dried_kelp_block = new Block("dried_kelp_block");
	dropper = new Block("dropper");
	emerald_block = new Block("emerald_block");
	emerald_ore = new Block("emerald_ore");
	enchanting_table = new Block("enchanting_table");
	end_brick_stairs = new Block("end_brick_stairs");
	end_bricks = new Block("end_bricks");
	end_gateway = new Block("end_gateway");
	end_portal = new Block("end_portal");
	end_portal_frame = new Block("end_portal_frame");
	end_rod = new Block("end_rod");
	end_stone = new Block("end_stone");
	ender_chest = new Block("ender_chest");
	farmland = new Block("farmland");
	fence = new Block("fence");
	fence_gate = new Block("fence_gate");
	fire = new Block("fire");
	fletching_table = new Block("fletching_table");
	flower_pot = new Block("flower_pot");
	flowing_lava = (new LiquidBlock("flowing_lava"))->setRenderType(RenderType::Liquid)->setRenderLayer(RenderLayer::Transparent);
	flowing_water = (new LiquidBlock("flowing_water"))->setRenderType(RenderType::Liquid)->setRenderLayer(RenderLayer::Transparent);
	frame = new Block("frame");
	frosted_ice = new Block("frosted_ice");
	furnace = new Block("furnace");
	glass = new Block("glass");
	glass_pane = new Block("glass_pane");
	glowingobsidian = new Block("glowingobsidian");
	glowstone = new Block("glowstone");
	gold_block = new Block("gold_block");
	gold_ore = new Block("gold_ore");
	golden_rail = new Block("golden_rail");
	granite_stairs = new Block("granite_stairs");
	grass = (new Block("grass"))->setTint(Tint::Grass);
	grass_path = new Block("grass_path");
	gravel = new Block("gravel");
	gray_glazed_terracotta = new Block("gray_glazed_terracotta");
	green_glazed_terracotta = new Block("green_glazed_terracotta");
	grindstone = new Block("grindstone");
	hardened_clay = new Block("hardened_clay");
	hay_block = new Block("hay_block");
	heavy_weighted_pressure_plate = new Block("heavy_weighted_pressure_plate");
	hopper = new Block("hopper");
	ice = new Block("ice");
	info_update = new Block("info_update");
	info_update2 = new Block("info_update2");
	invisibleBedrock = new Block("invisibleBedrock");
	iron_bars = (new Block("iron_bars"))->setRenderType(RenderType::Pane);
	iron_block = new Block("iron_block");
	iron_door = new Block("iron_door");
	iron_ore = new Block("iron_ore");
	iron_trapdoor = new Block("iron_trapdoor");
	jigsaw = new Block("jigsaw");
	jukebox = new Block("jukebox");
	jungle_button = new Block("jungle_button");
	jungle_door = new Block("jungle_door");
	jungle_fence_gate = new Block("jungle_fence_gate");
	jungle_pressure_plate = new Block("jungle_pressure_plate");
	jungle_stairs = new Block("jungle_stairs");
	jungle_standing_sign = new Block("jungle_standing_sign");
	jungle_trapdoor = new Block("jungle_trapdoor");
	jungle_wall_sign = new Block("jungle_wall_sign");
	kelp = new Block("kelp");
	ladder = new Block("ladder");
	lantern = new Block("lantern");
	lapis_block = new Block("lapis_block");
	lapis_ore = new Block("lapis_ore");
	lava = (new LiquidBlock("lava"))->setRenderType(RenderType::Liquid)->setRenderLayer(RenderLayer::Transparent);
	lava_cauldron = new Block("lava_cauldron");
	leaves = (new Block("leaves"))->setRenderType(RenderType::Leaves)->setTint(Tint::Foliage)->setRenderLayer(RenderLayer::Cutout);
	leaves2 = (new Block("leaves2"))->setRenderType(RenderType::Leaves)->setTint(Tint::Foliage)->setRenderLayer(RenderLayer::Cutout);
	lectern = new Block("lectern");
	lever = new Block("lever");
	light_block = new Block("light_block");
	light_blue_glazed_terracotta = new Block("light_blue_glazed_terracotta");
	light_weighted_pressure_plate = new Block("light_weighted_pressure_plate");
	lime_glazed_terracotta = new Block("lime_glazed_terracotta");
	lit_blast_furnace = new Block("lit_blast_furnace");
	lit_furnace = new Block("lit_furnace");
	lit_pumpkin = new Block("lit_pumpkin");
	lit_redstone_lamp = new Block("lit_redstone_lamp");
	lit_redstone_ore = new Block("lit_redstone_ore");
	lit_smoker = new Block("lit_smoker");
	log = new Block("log");
	log2 = new Block("log2");
	loom = new Block("loom");
	magenta_glazed_terracotta = new Block("magenta_glazed_terracotta");
	magma = new Block("magma");
	melon_block = new Block("melon_block");
	melon_stem = new Block("melon_stem");
	mob_spawner = new Block("mob_spawner");
	monster_egg = new Block("monster_egg");
	mossy_cobblestone = new Block("mossy_cobblestone");
	mossy_cobblestone_stairs = new Block("mossy_cobblestone_stairs");
	mossy_stone_brick_stairs = new Block("mossy_stone_brick_stairs");
	movingBlock = new Block("movingBlock");
	mycelium = new Block("mycelium");
	nether_brick = new Block("nether_brick");
	nether_brick_fence = new Block("nether_brick_fence");
	nether_brick_stairs = new Block("nether_brick_stairs");
	nether_wart = new Block("nether_wart");
	nether_wart_block = new Block("nether_wart_block");
	netherrack = new Block("netherrack");
	netherreactor = new Block("netherreactor");
	normal_stone_stairs = new Block("normal_stone_stairs");
	noteblock = new Block("noteblock");
	oak_stairs = new Block("oak_stairs");
	observer = new Block("observer");
	obsidian = new Block("obsidian");
	orange_glazed_terracotta = new Block("orange_glazed_terracotta");
	packed_ice = new Block("packed_ice");
	pink_glazed_terracotta = new Block("pink_glazed_terracotta");
	piston = new Block("piston");
	pistonArmCollision = new Block("pistonArmCollision");
	planks = new Block("planks");
	podzol = new Block("podzol");
	polished_andesite_stairs = new Block("polished_andesite_stairs");
	polished_diorite_stairs = new Block("polished_diorite_stairs");
	polished_granite_stairs = new Block("polished_granite_stairs");
	portal = new Block("portal");
	potatoes = new Block("potatoes");
	powered_comparator = new Block("powered_comparator");
	powered_repeater = new Block("powered_repeater");
	prismarine = new Block("prismarine");
	prismarine_bricks_stairs = new Block("prismarine_bricks_stairs");
	prismarine_stairs = new Block("prismarine_stairs");
	pumpkin = new Block("pumpkin");
	pumpkin_stem = new Block("pumpkin_stem");
	purple_glazed_terracotta = new Block("purple_glazed_terracotta");
	purpur_block = new Block("purpur_block");
	purpur_stairs = new Block("purpur_stairs");
	quartz_block = new Block("quartz_block");
	quartz_ore = new Block("quartz_ore");
	quartz_stairs = new Block("quartz_stairs");
	rail = new Block("rail");
	red_flower = (new Block("red_flower"))->setRenderType(RenderType::Cross)->setRenderLayer(RenderLayer::Cutout);
	red_glazed_terracotta = new Block("red_glazed_terracotta");
	red_mushroom = new Block("red_mushroom");
	red_mushroom_block = new Block("red_mushroom_block");
	red_nether_brick = new Block("red_nether_brick");
	red_nether_brick_stairs = new Block("red_nether_brick_stairs");
	red_sandstone = new Block("red_sandstone");
	red_sandstone_stairs = new Block("red_sandstone_stairs");
	redstone_block = new Block("redstone_block");
	redstone_lamp = new Block("redstone_lamp");
	redstone_ore = new Block("redstone_ore");
	redstone_torch = new Block("redstone_torch");
	redstone_wire = new Block("redstone_wire");
	reeds = new Block("reeds");
	repeating_command_block = new Block("repeating_command_block");
	reserved6 = new Block("reserved6");
	sand = new Block("sand");
	sandstone = new Block("sandstone");
	sandstone_stairs = new Block("sandstone_stairs");
	sapling = new Block("sapling");
	scaffolding = new Block("scaffolding");
	seaLantern = new Block("seaLantern");
	sea_pickle = new Block("sea_pickle");
	seagrass = new Block("seagrass");
	shulker_box = new Block("shulker_box");
	silver_glazed_terracotta = new Block("silver_glazed_terracotta");
	skull = new Block("skull");
	slime = new Block("slime");
	smithing_table = new Block("smithing_table");
	smoker = new Block("smoker");
	smooth_quartz_stairs = new Block("smooth_quartz_stairs");
	smooth_red_sandstone_stairs = new Block("smooth_red_sandstone_stairs");
	smooth_sandstone_stairs = new Block("smooth_sandstone_stairs");
	smooth_stone = new Block("smooth_stone");
	snow = new Block("snow");
	snow_layer = new Block("snow_layer");
	soul_sand = new Block("soul_sand");
	sponge = new Block("sponge");
	spruce_button = new Block("spruce_button");
	spruce_door = new Block("spruce_door");
	spruce_fence_gate = new Block("spruce_fence_gate");
	spruce_pressure_plate = new Block("spruce_pressure_plate");
	spruce_stairs = new Block("spruce_stairs");
	spruce_standing_sign = new Block("spruce_standing_sign");
	spruce_trapdoor = new Block("spruce_trapdoor");
	spruce_wall_sign = new Block("spruce_wall_sign");
	stained_glass = new Block("stained_glass");
	stained_glass_pane = new Block("stained_glass_pane");
	stained_hardened_clay = new Block("stained_hardened_clay");
	standing_banner = new Block("standing_banner");
	standing_sign = new Block("standing_sign");
	stickyPistonArmCollision = new Block("stickyPistonArmCollision");
	sticky_piston = new Block("sticky_piston");
	stone = new Block("stone");
	stone_brick_stairs = new Block("stone_brick_stairs");
	stone_button = new Block("stone_button");
	stone_pressure_plate = new Block("stone_pressure_plate");
	stone_slab = new Block("stone_slab");
	stone_slab2 = new Block("stone_slab2");
	stone_slab3 = new Block("stone_slab3");
	stone_slab4 = new Block("stone_slab4");
	stone_stairs = new Block("stone_stairs");
	stonebrick = new Block("stonebrick");
	stonecutter = new Block("stonecutter");
	stonecutter_block = new Block("stonecutter_block");
	stripped_acacia_log = new Block("stripped_acacia_log");
	stripped_birch_log = new Block("stripped_birch_log");
	stripped_dark_oak_log = new Block("stripped_dark_oak_log");
	stripped_jungle_log = new Block("stripped_jungle_log");
	stripped_oak_log = new Block("stripped_oak_log");
	stripped_spruce_log = new Block("stripped_spruce_log");
	structure_block = new Block("structure_block");
	structure_void = new Block("structure_void");
	sweet_berry_bush = new Block("sweet_berry_bush");
	tallgrass = (new Block("tallgrass"))->setRenderType(RenderType::Cross)->setTint(Tint::Grass)->setRenderLayer(RenderLayer::Cutout);
	tnt = new Block("tnt");
	torch = new Block("torch");
	trapdoor = new Block("trapdoor");
	trapped_chest = new Block("trapped_chest");
	tripWire = new Block("tripWire");
	tripwire_hook = new Block("tripwire_hook");
	turtle_egg = new Block("turtle_egg");
	undyed_shulker_box = new Block("undyed_shulker_box");
	unlit_redstone_torch = new Block("unlit_redstone_torch");
	unpowered_comparator = new Block("unpowered_comparator");
	unpowered_repeater = new Block("unpowered_repeater");
	vine = new Block("vine");
	wall_banner = new Block("wall_banner");
	wall_sign = new Block("wall_sign");
	water = (new LiquidBlock("water"))->setRenderType(RenderType::Liquid)->setRenderLayer(RenderLayer::Transparent);
	waterlily = new Block("waterlily");
	web = new Block("web");
	wheat = new Block("wheat");
	white_glazed_terracotta = new Block("white_glazed_terracotta");
	wither_rose = new Block("wither_rose");
	wood = new Block("wood");
	wooden_button = new Block("wooden_button");
	wooden_door = new Block("wooden_door");
	wooden_pressure_plate = new Block("wooden_pressure_plate");
	wooden_slab = new Block("wooden_slab");
	wool = new Block("wool");
	yellow_flower = (new Block("yellow_flower"))->setRenderType(RenderType::Cross)->setRenderLayer(RenderLayer::Cutout);
	yellow_glazed_terracotta = new Block("yellow_glazed_terracotta");

	id_to_block.resize(5000);
}

void Block::registerBlock(BlockTable &pallete, const std::string &name, Block *block) {
    id_to_block[(int) pallete.getId(name)] = block;
}

void Block::registerBlocks(BlockTable& pallete) {
    registerBlock(pallete, "acacia_button", acacia_button);
    registerBlock(pallete, "acacia_door", acacia_door);
    registerBlock(pallete, "acacia_fence_gate", acacia_fence_gate);
    registerBlock(pallete, "acacia_pressure_plate", acacia_pressure_plate);
    registerBlock(pallete, "acacia_stairs", acacia_stairs);
    registerBlock(pallete, "acacia_standing_sign", acacia_standing_sign);
    registerBlock(pallete, "acacia_trapdoor", acacia_trapdoor);
    registerBlock(pallete, "acacia_wall_sign", acacia_wall_sign);
    registerBlock(pallete, "activator_rail", activator_rail);
    registerBlock(pallete, "air", air);
    registerBlock(pallete, "allow", allow);
    registerBlock(pallete, "andesite_stairs", andesite_stairs);
    registerBlock(pallete, "anvil", anvil);
    registerBlock(pallete, "bamboo", bamboo);
    registerBlock(pallete, "bamboo_sapling", bamboo_sapling);
    registerBlock(pallete, "barrel", barrel);
    registerBlock(pallete, "barrier", barrier);
    registerBlock(pallete, "beacon", beacon);
    registerBlock(pallete, "bed", bed);
    registerBlock(pallete, "bedrock", bedrock);
    registerBlock(pallete, "beetroot", beetroot);
    registerBlock(pallete, "bell", bell);
    registerBlock(pallete, "birch_button", birch_button);
    registerBlock(pallete, "birch_door", birch_door);
    registerBlock(pallete, "birch_fence_gate", birch_fence_gate);
    registerBlock(pallete, "birch_pressure_plate", birch_pressure_plate);
    registerBlock(pallete, "birch_stairs", birch_stairs);
    registerBlock(pallete, "birch_standing_sign", birch_standing_sign);
    registerBlock(pallete, "birch_trapdoor", birch_trapdoor);
    registerBlock(pallete, "birch_wall_sign", birch_wall_sign);
    registerBlock(pallete, "black_glazed_terracotta", black_glazed_terracotta);
    registerBlock(pallete, "blast_furnace", blast_furnace);
    registerBlock(pallete, "blue_glazed_terracotta", blue_glazed_terracotta);
    registerBlock(pallete, "blue_ice", blue_ice);
    registerBlock(pallete, "bone_block", bone_block);
    registerBlock(pallete, "bookshelf", bookshelf);
    registerBlock(pallete, "border_block", border_block);
    registerBlock(pallete, "brewing_stand", brewing_stand);
    registerBlock(pallete, "brick_block", brick_block);
    registerBlock(pallete, "brick_stairs", brick_stairs);
    registerBlock(pallete, "brown_glazed_terracotta", brown_glazed_terracotta);
    registerBlock(pallete, "brown_mushroom", brown_mushroom);
    registerBlock(pallete, "brown_mushroom_block", brown_mushroom_block);
    registerBlock(pallete, "bubble_column", bubble_column);
    registerBlock(pallete, "cactus", cactus);
    registerBlock(pallete, "cake", cake);
    registerBlock(pallete, "camera", camera);
    registerBlock(pallete, "campfire", campfire);
    registerBlock(pallete, "carpet", carpet);
    registerBlock(pallete, "carrots", carrots);
    registerBlock(pallete, "cartography_table", cartography_table);
    registerBlock(pallete, "carved_pumpkin", carved_pumpkin);
    registerBlock(pallete, "cauldron", cauldron);
    registerBlock(pallete, "chain_command_block", chain_command_block);
    registerBlock(pallete, "chest", chest);
    registerBlock(pallete, "chorus_flower", chorus_flower);
    registerBlock(pallete, "chorus_plant", chorus_plant);
    registerBlock(pallete, "clay", clay);
    registerBlock(pallete, "coal_block", coal_block);
    registerBlock(pallete, "coal_ore", coal_ore);
    registerBlock(pallete, "cobblestone", cobblestone);
    registerBlock(pallete, "cobblestone_wall", cobblestone_wall);
    registerBlock(pallete, "cocoa", cocoa);
    registerBlock(pallete, "command_block", command_block);
    registerBlock(pallete, "composter", composter);
    registerBlock(pallete, "concrete", concrete);
    registerBlock(pallete, "concretePowder", concretePowder);
    registerBlock(pallete, "conduit", conduit);
    registerBlock(pallete, "coral", coral);
    registerBlock(pallete, "coral_block", coral_block);
    registerBlock(pallete, "coral_fan", coral_fan);
    registerBlock(pallete, "coral_fan_dead", coral_fan_dead);
    registerBlock(pallete, "coral_fan_hang", coral_fan_hang);
    registerBlock(pallete, "coral_fan_hang2", coral_fan_hang2);
    registerBlock(pallete, "coral_fan_hang3", coral_fan_hang3);
    registerBlock(pallete, "crafting_table", crafting_table);
    registerBlock(pallete, "cyan_glazed_terracotta", cyan_glazed_terracotta);
    registerBlock(pallete, "dark_oak_button", dark_oak_button);
    registerBlock(pallete, "dark_oak_door", dark_oak_door);
    registerBlock(pallete, "dark_oak_fence_gate", dark_oak_fence_gate);
    registerBlock(pallete, "dark_oak_pressure_plate", dark_oak_pressure_plate);
    registerBlock(pallete, "dark_oak_stairs", dark_oak_stairs);
    registerBlock(pallete, "dark_oak_trapdoor", dark_oak_trapdoor);
    registerBlock(pallete, "dark_prismarine_stairs", dark_prismarine_stairs);
    registerBlock(pallete, "darkoak_standing_sign", darkoak_standing_sign);
    registerBlock(pallete, "darkoak_wall_sign", darkoak_wall_sign);
    registerBlock(pallete, "daylight_detector", daylight_detector);
    registerBlock(pallete, "daylight_detector_inverted", daylight_detector_inverted);
    registerBlock(pallete, "deadbush", deadbush);
    registerBlock(pallete, "deny", deny);
    registerBlock(pallete, "detector_rail", detector_rail);
    registerBlock(pallete, "diamond_block", diamond_block);
    registerBlock(pallete, "diamond_ore", diamond_ore);
    registerBlock(pallete, "diorite_stairs", diorite_stairs);
    registerBlock(pallete, "dirt", dirt);
    registerBlock(pallete, "dispenser", dispenser);
    registerBlock(pallete, "double_plant", double_plant);
    registerBlock(pallete, "double_stone_slab", double_stone_slab);
    registerBlock(pallete, "double_stone_slab2", double_stone_slab2);
    registerBlock(pallete, "double_stone_slab3", double_stone_slab3);
    registerBlock(pallete, "double_stone_slab4", double_stone_slab4);
    registerBlock(pallete, "double_wooden_slab", double_wooden_slab);
    registerBlock(pallete, "dragon_egg", dragon_egg);
    registerBlock(pallete, "dried_kelp_block", dried_kelp_block);
    registerBlock(pallete, "dropper", dropper);
    registerBlock(pallete, "emerald_block", emerald_block);
    registerBlock(pallete, "emerald_ore", emerald_ore);
    registerBlock(pallete, "enchanting_table", enchanting_table);
    registerBlock(pallete, "end_brick_stairs", end_brick_stairs);
    registerBlock(pallete, "end_bricks", end_bricks);
    registerBlock(pallete, "end_gateway", end_gateway);
    registerBlock(pallete, "end_portal", end_portal);
    registerBlock(pallete, "end_portal_frame", end_portal_frame);
    registerBlock(pallete, "end_rod", end_rod);
    registerBlock(pallete, "end_stone", end_stone);
    registerBlock(pallete, "ender_chest", ender_chest);
    registerBlock(pallete, "farmland", farmland);
    registerBlock(pallete, "fence", fence);
    registerBlock(pallete, "fence_gate", fence_gate);
    registerBlock(pallete, "fire", fire);
    registerBlock(pallete, "fletching_table", fletching_table);
    registerBlock(pallete, "flower_pot", flower_pot);
    registerBlock(pallete, "flowing_lava", flowing_lava);
    registerBlock(pallete, "flowing_water", flowing_water);
    registerBlock(pallete, "frame", frame);
    registerBlock(pallete, "frosted_ice", frosted_ice);
    registerBlock(pallete, "furnace", furnace);
    registerBlock(pallete, "glass", glass);
    registerBlock(pallete, "glass_pane", glass_pane);
    registerBlock(pallete, "glowingobsidian", glowingobsidian);
    registerBlock(pallete, "glowstone", glowstone);
    registerBlock(pallete, "gold_block", gold_block);
    registerBlock(pallete, "gold_ore", gold_ore);
    registerBlock(pallete, "golden_rail", golden_rail);
    registerBlock(pallete, "granite_stairs", granite_stairs);
    registerBlock(pallete, "grass", grass);
    registerBlock(pallete, "grass_path", grass_path);
    registerBlock(pallete, "gravel", gravel);
    registerBlock(pallete, "gray_glazed_terracotta", gray_glazed_terracotta);
    registerBlock(pallete, "green_glazed_terracotta", green_glazed_terracotta);
    registerBlock(pallete, "grindstone", grindstone);
    registerBlock(pallete, "hardened_clay", hardened_clay);
    registerBlock(pallete, "hay_block", hay_block);
    registerBlock(pallete, "heavy_weighted_pressure_plate", heavy_weighted_pressure_plate);
    registerBlock(pallete, "hopper", hopper);
    registerBlock(pallete, "ice", ice);
    registerBlock(pallete, "info_update", info_update);
    registerBlock(pallete, "info_update2", info_update2);
    registerBlock(pallete, "invisibleBedrock", invisibleBedrock);
    registerBlock(pallete, "iron_bars", iron_bars);
    registerBlock(pallete, "iron_block", iron_block);
    registerBlock(pallete, "iron_door", iron_door);
    registerBlock(pallete, "iron_ore", iron_ore);
    registerBlock(pallete, "iron_trapdoor", iron_trapdoor);
    registerBlock(pallete, "jigsaw", jigsaw);
    registerBlock(pallete, "jukebox", jukebox);
    registerBlock(pallete, "jungle_button", jungle_button);
    registerBlock(pallete, "jungle_door", jungle_door);
    registerBlock(pallete, "jungle_fence_gate", jungle_fence_gate);
    registerBlock(pallete, "jungle_pressure_plate", jungle_pressure_plate);
    registerBlock(pallete, "jungle_stairs", jungle_stairs);
    registerBlock(pallete, "jungle_standing_sign", jungle_standing_sign);
    registerBlock(pallete, "jungle_trapdoor", jungle_trapdoor);
    registerBlock(pallete, "jungle_wall_sign", jungle_wall_sign);
    registerBlock(pallete, "kelp", kelp);
    registerBlock(pallete, "ladder", ladder);
    registerBlock(pallete, "lantern", lantern);
    registerBlock(pallete, "lapis_block", lapis_block);
    registerBlock(pallete, "lapis_ore", lapis_ore);
    registerBlock(pallete, "lava", lava);
    registerBlock(pallete, "lava_cauldron", lava_cauldron);
    registerBlock(pallete, "leaves", leaves);
    registerBlock(pallete, "leaves2", leaves2);
    registerBlock(pallete, "lectern", lectern);
    registerBlock(pallete, "lever", lever);
    registerBlock(pallete, "light_block", light_block);
    registerBlock(pallete, "light_blue_glazed_terracotta", light_blue_glazed_terracotta);
    registerBlock(pallete, "light_weighted_pressure_plate", light_weighted_pressure_plate);
    registerBlock(pallete, "lime_glazed_terracotta", lime_glazed_terracotta);
    registerBlock(pallete, "lit_blast_furnace", lit_blast_furnace);
    registerBlock(pallete, "lit_furnace", lit_furnace);
    registerBlock(pallete, "lit_pumpkin", lit_pumpkin);
    registerBlock(pallete, "lit_redstone_lamp", lit_redstone_lamp);
    registerBlock(pallete, "lit_redstone_ore", lit_redstone_ore);
    registerBlock(pallete, "lit_smoker", lit_smoker);
    registerBlock(pallete, "log", log);
    registerBlock(pallete, "log2", log2);
    registerBlock(pallete, "loom", loom);
    registerBlock(pallete, "magenta_glazed_terracotta", magenta_glazed_terracotta);
    registerBlock(pallete, "magma", magma);
    registerBlock(pallete, "melon_block", melon_block);
    registerBlock(pallete, "melon_stem", melon_stem);
    registerBlock(pallete, "mob_spawner", mob_spawner);
    registerBlock(pallete, "monster_egg", monster_egg);
    registerBlock(pallete, "mossy_cobblestone", mossy_cobblestone);
    registerBlock(pallete, "mossy_cobblestone_stairs", mossy_cobblestone_stairs);
    registerBlock(pallete, "mossy_stone_brick_stairs", mossy_stone_brick_stairs);
    registerBlock(pallete, "movingBlock", movingBlock);
    registerBlock(pallete, "mycelium", mycelium);
    registerBlock(pallete, "nether_brick", nether_brick);
    registerBlock(pallete, "nether_brick_fence", nether_brick_fence);
    registerBlock(pallete, "nether_brick_stairs", nether_brick_stairs);
    registerBlock(pallete, "nether_wart", nether_wart);
    registerBlock(pallete, "nether_wart_block", nether_wart_block);
    registerBlock(pallete, "netherrack", netherrack);
    registerBlock(pallete, "netherreactor", netherreactor);
    registerBlock(pallete, "normal_stone_stairs", normal_stone_stairs);
    registerBlock(pallete, "noteblock", noteblock);
    registerBlock(pallete, "oak_stairs", oak_stairs);
    registerBlock(pallete, "observer", observer);
    registerBlock(pallete, "obsidian", obsidian);
    registerBlock(pallete, "orange_glazed_terracotta", orange_glazed_terracotta);
    registerBlock(pallete, "packed_ice", packed_ice);
    registerBlock(pallete, "pink_glazed_terracotta", pink_glazed_terracotta);
    registerBlock(pallete, "piston", piston);
    registerBlock(pallete, "pistonArmCollision", pistonArmCollision);
    registerBlock(pallete, "planks", planks);
    registerBlock(pallete, "podzol", podzol);
    registerBlock(pallete, "polished_andesite_stairs", polished_andesite_stairs);
    registerBlock(pallete, "polished_diorite_stairs", polished_diorite_stairs);
    registerBlock(pallete, "polished_granite_stairs", polished_granite_stairs);
    registerBlock(pallete, "portal", portal);
    registerBlock(pallete, "potatoes", potatoes);
    registerBlock(pallete, "powered_comparator", powered_comparator);
    registerBlock(pallete, "powered_repeater", powered_repeater);
    registerBlock(pallete, "prismarine", prismarine);
    registerBlock(pallete, "prismarine_bricks_stairs", prismarine_bricks_stairs);
    registerBlock(pallete, "prismarine_stairs", prismarine_stairs);
    registerBlock(pallete, "pumpkin", pumpkin);
    registerBlock(pallete, "pumpkin_stem", pumpkin_stem);
    registerBlock(pallete, "purple_glazed_terracotta", purple_glazed_terracotta);
    registerBlock(pallete, "purpur_block", purpur_block);
    registerBlock(pallete, "purpur_stairs", purpur_stairs);
    registerBlock(pallete, "quartz_block", quartz_block);
    registerBlock(pallete, "quartz_ore", quartz_ore);
    registerBlock(pallete, "quartz_stairs", quartz_stairs);
    registerBlock(pallete, "rail", rail);
    registerBlock(pallete, "red_flower", red_flower);
    registerBlock(pallete, "red_glazed_terracotta", red_glazed_terracotta);
    registerBlock(pallete, "red_mushroom", red_mushroom);
    registerBlock(pallete, "red_mushroom_block", red_mushroom_block);
    registerBlock(pallete, "red_nether_brick", red_nether_brick);
    registerBlock(pallete, "red_nether_brick_stairs", red_nether_brick_stairs);
    registerBlock(pallete, "red_sandstone", red_sandstone);
    registerBlock(pallete, "red_sandstone_stairs", red_sandstone_stairs);
    registerBlock(pallete, "redstone_block", redstone_block);
    registerBlock(pallete, "redstone_lamp", redstone_lamp);
    registerBlock(pallete, "redstone_ore", redstone_ore);
    registerBlock(pallete, "redstone_torch", redstone_torch);
    registerBlock(pallete, "redstone_wire", redstone_wire);
    registerBlock(pallete, "reeds", reeds);
    registerBlock(pallete, "repeating_command_block", repeating_command_block);
    registerBlock(pallete, "reserved6", reserved6);
    registerBlock(pallete, "sand", sand);
    registerBlock(pallete, "sandstone", sandstone);
    registerBlock(pallete, "sandstone_stairs", sandstone_stairs);
    registerBlock(pallete, "sapling", sapling);
    registerBlock(pallete, "scaffolding", scaffolding);
    registerBlock(pallete, "seaLantern", seaLantern);
    registerBlock(pallete, "sea_pickle", sea_pickle);
    registerBlock(pallete, "seagrass", seagrass);
    registerBlock(pallete, "shulker_box", shulker_box);
    registerBlock(pallete, "silver_glazed_terracotta", silver_glazed_terracotta);
    registerBlock(pallete, "skull", skull);
    registerBlock(pallete, "slime", slime);
    registerBlock(pallete, "smithing_table", smithing_table);
    registerBlock(pallete, "smoker", smoker);
    registerBlock(pallete, "smooth_quartz_stairs", smooth_quartz_stairs);
    registerBlock(pallete, "smooth_red_sandstone_stairs", smooth_red_sandstone_stairs);
    registerBlock(pallete, "smooth_sandstone_stairs", smooth_sandstone_stairs);
    registerBlock(pallete, "smooth_stone", smooth_stone);
    registerBlock(pallete, "snow", snow);
    registerBlock(pallete, "snow_layer", snow_layer);
    registerBlock(pallete, "soul_sand", soul_sand);
    registerBlock(pallete, "sponge", sponge);
    registerBlock(pallete, "spruce_button", spruce_button);
    registerBlock(pallete, "spruce_door", spruce_door);
    registerBlock(pallete, "spruce_fence_gate", spruce_fence_gate);
    registerBlock(pallete, "spruce_pressure_plate", spruce_pressure_plate);
    registerBlock(pallete, "spruce_stairs", spruce_stairs);
    registerBlock(pallete, "spruce_standing_sign", spruce_standing_sign);
    registerBlock(pallete, "spruce_trapdoor", spruce_trapdoor);
    registerBlock(pallete, "spruce_wall_sign", spruce_wall_sign);
    registerBlock(pallete, "stained_glass", stained_glass);
    registerBlock(pallete, "stained_glass_pane", stained_glass_pane);
    registerBlock(pallete, "stained_hardened_clay", stained_hardened_clay);
    registerBlock(pallete, "standing_banner", standing_banner);
    registerBlock(pallete, "standing_sign", standing_sign);
    registerBlock(pallete, "stickyPistonArmCollision", stickyPistonArmCollision);
    registerBlock(pallete, "sticky_piston", sticky_piston);
    registerBlock(pallete, "stone", stone);
    registerBlock(pallete, "stone_brick_stairs", stone_brick_stairs);
    registerBlock(pallete, "stone_button", stone_button);
    registerBlock(pallete, "stone_pressure_plate", stone_pressure_plate);
    registerBlock(pallete, "stone_slab", stone_slab);
    registerBlock(pallete, "stone_slab2", stone_slab2);
    registerBlock(pallete, "stone_slab3", stone_slab3);
    registerBlock(pallete, "stone_slab4", stone_slab4);
    registerBlock(pallete, "stone_stairs", stone_stairs);
    registerBlock(pallete, "stonebrick", stonebrick);
    registerBlock(pallete, "stonecutter", stonecutter);
    registerBlock(pallete, "stonecutter_block", stonecutter_block);
    registerBlock(pallete, "stripped_acacia_log", stripped_acacia_log);
    registerBlock(pallete, "stripped_birch_log", stripped_birch_log);
    registerBlock(pallete, "stripped_dark_oak_log", stripped_dark_oak_log);
    registerBlock(pallete, "stripped_jungle_log", stripped_jungle_log);
    registerBlock(pallete, "stripped_oak_log", stripped_oak_log);
    registerBlock(pallete, "stripped_spruce_log", stripped_spruce_log);
    registerBlock(pallete, "structure_block", structure_block);
    registerBlock(pallete, "structure_void", structure_void);
    registerBlock(pallete, "sweet_berry_bush", sweet_berry_bush);
    registerBlock(pallete, "tallgrass", tallgrass);
    registerBlock(pallete, "tnt", tnt);
    registerBlock(pallete, "torch", torch);
    registerBlock(pallete, "trapdoor", trapdoor);
    registerBlock(pallete, "trapped_chest", trapped_chest);
    registerBlock(pallete, "tripWire", tripWire);
    registerBlock(pallete, "tripwire_hook", tripwire_hook);
    registerBlock(pallete, "turtle_egg", turtle_egg);
    registerBlock(pallete, "undyed_shulker_box", undyed_shulker_box);
    registerBlock(pallete, "unlit_redstone_torch", unlit_redstone_torch);
    registerBlock(pallete, "unpowered_comparator", unpowered_comparator);
    registerBlock(pallete, "unpowered_repeater", unpowered_repeater);
    registerBlock(pallete, "vine", vine);
    registerBlock(pallete, "wall_banner", wall_banner);
    registerBlock(pallete, "wall_sign", wall_sign);
    registerBlock(pallete, "water", water);
    registerBlock(pallete, "waterlily", waterlily);
    registerBlock(pallete, "web", web);
    registerBlock(pallete, "wheat", wheat);
    registerBlock(pallete, "white_glazed_terracotta", white_glazed_terracotta);
    registerBlock(pallete, "wither_rose", wither_rose);
    registerBlock(pallete, "wood", wood);
    registerBlock(pallete, "wooden_button", wooden_button);
    registerBlock(pallete, "wooden_door", wooden_door);
    registerBlock(pallete, "wooden_pressure_plate", wooden_pressure_plate);
    registerBlock(pallete, "wooden_slab", wooden_slab);
    registerBlock(pallete, "wool", wool);
    registerBlock(pallete, "yellow_flower", yellow_flower);
    registerBlock(pallete, "yellow_glazed_terracotta", yellow_glazed_terracotta);
}